### ISSUE TITLE
Feature: BlockControls button

### ISSUE THREAD

**Issue by MWDelaney** [roots/bud#1]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

We should add a BlockControls button along the lines of the ones included in `core/media-text` or `core/cover` for editing the background image.

**Comment by kellymears** [comment]
https://github.com/roots/bud/pull/38 now works with this API. Keeping this open till we've built stand-alone generators.

**Comment by kellymears** [comment]
This issue has been moved to https://github.com/roots/bud-generators/issues/3
