### ISSUE TITLE
[bug] yarn build fails at linting scss files

### ISSUE THREAD

**Issue by mensch** [roots/bud#1019]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Expected Behavior

After running `yarn build` a directory with the packaged assets should be created.

### Actual Behavior

The `build` (and `dev`) task fails at processing the SCSS files, reverting to the CSS linter. Resulting in errors like: _Unexpected unknown at-rule "@use"  at-rule-no-unknown_

### Steps To Reproduce

1. Initialise empty Roots Sage theme
2. Remove Tailwind and related config files (I don't use Tailwind)
3. Install dependencies
3. Add `bud-sass`
4. Run `yarn bud install`
5. Run `yarn install` again
6. Run `yarn build`

### version

@roots/bud/5.2.0 darwin-x64 node-v17.4.0

### What package manager are you using?

yarn berry

### version

3.1.1

### Are you using pnpm?

- [ ] yes
- [X] no

### Configuration

```shell
const SVGSpritemapPlugin = require('svg-spritemap-webpack-plugin');

/**
 * @typedef {import('@roots/bud').Bud} bud
 *
 * @param {bud} app
 */
module.exports = (app) =>
  app
    /**
     * Application entrypoints
     *
     * Paths are relative to your resources directory
     */
    .entry({
      app: ['scripts/app.js', 'styles/app.css'],
      editor: ['scripts/editor.js', 'styles/editor.css'],
    })

    /**
     * These files should be processed as part of the build
     * even if they are not explicitly imported in application assets.
     */
    .assets([app.path('src', 'images')])

    /**
     * These files will trigger a full page reload
     * when modified.
     */
    .watch(['resources/views/**/*.blade.php', 'app/View/**/*.php'])

    /**
     * Target URL to be proxied by the dev server.
     *
     * This is your local dev server.
     */
    .proxy('http://testsetup.test')

    /**
     * Generate SVG sprite based on available icons
     *
     */
    .use(
      new SVGSpritemapPlugin('resources/images/icons/*.svg', {
        output: {
          filename: 'icons.svg',
          chunk: {keep: true},
          svgo: false,
        },
        sprite: {
          prefix: false,
        },
      }),
    );
```

### Relevant .budfiles

Paths in the files below have been redacted.
[budfiles.zip](https://github.com/roots/bud/files/7942099/budfiles.zip)

**Comment by kellymears** [comment]
you need to configure stylelint for sass (or remove it). there is a preset config exported by @roots/bud-sass. 

the release notes for 5.2.0 cover it in more detail.

**Comment by mensch** [comment]
Thanks! Of course I forgot to look at the release notes...

My .stylelintrc now looks like this and build is working:
```
{
  "extends": [
    "@roots/sage/stylelint-config",
    "@roots/bud-sass/stylelint-config"
  ]
}
```
