### ISSUE TITLE
[bug] bud doctor: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by markjaquith** [roots/bud#1021]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Expected Behavior

`bud doctor` to run as it did in 5.1.0

### Actual Behavior

> TypeError: Cannot convert undefined or null to object

### Steps To Reproduce

Check out Sage at `60e4c24d9713d1c4c6e51e7a46daa1fe48695f2c` and then run `yarn` and then `yarn bud doctor`

### version

@roots/bud/5.2.0 darwin-x64 node-v16.13.2

### What package manager are you using?

yarn classic

### version

1.22.5

### Are you using pnpm?

- [ ] yes
- [X] no

**Comment by kellymears** [comment]
thanks for the report. it doesn't surprise me that this is janked since so much has changed on the road to 5.2.0 and there is no unit or integration testing for this command yet.
