### ISSUE TITLE
[bug] bud-sass not installing on final yarn command: "could not find a copy of eslint to link"

### ISSUE THREAD

**Issue by sitesandsuch** [roots/bud#1095]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Expected Behavior

Installing bud-sass on a clean install of roots/sage dev-main
Installation should run without errors

### Actual Behavior

On final step: yarn, error is generated:
An unexpected error occurred: "could not find a copy of eslint to link in /Users/kipara/Sites/ifleetltd/wwwroot/wp-content/themes/mytheme/node_modules/@roots/bud-eslint/node_modules".

On inspection that directory is empty.

I have removed @roots/bud-eslint and re-added. Same result.

### Steps To Reproduce

Clean install of sage/roots -dev-main
Run yarn - change domain
Run yarn dev -> success
Run yarn build -> success

Run yarn add @roots/bud-sass --dev
Run yarn -> error An unexpected error occurred: "could not find a copy of eslint to link in /Users/kipara/Sites/ifleetltd/wwwroot/wp-content/themes/mytheme/node_modules/@roots/bud-eslint/node_modules".

### version

@roots/bud/5.2.0 darwin-arm64 node-v16.13.1

### What package manager are you using?

yarn classic

### version

1.22.15

### Are you using pnpm?

- [ ] yes
- [X] no

### Logs

```shell
Arguments: 
  /Users/kipara/.nvm/versions/node/v16.13.1/bin/node /Users/kipara/.node/corepack/yarn/1.22.15/bin/yarn.js

PATH: 
  /Users/kipara/.nvm/versions/node/v16.13.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin

Yarn version: 
  1.22.15

Node version: 
  16.13.1

Platform: 
  darwin arm64

Trace: 
  Invariant Violation: could not find a copy of eslint to link in /Users/kipara/Sites/ifleetltd/wwwroot/wp-content/themes/mytheme/node_modules/@roots/bud-eslint/node_modules
      at invariant (/Users/kipara/.node/corepack/yarn/1.22.15/lib/cli.js:2314:15)
      at PackageLinker.<anonymous> (/Users/kipara/.node/corepack/yarn/1.22.15/lib/cli.js:48516:7)
      at Generator.next (<anonymous>)
      at step (/Users/kipara/.node/corepack/yarn/1.22.15/lib/cli.js:310:30)
      at /Users/kipara/.node/corepack/yarn/1.22.15/lib/cli.js:321:13
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

npm manifest: 
  {
    "name": "sage",
    "private": true,
    "bud": {
      "location": {
        "src": "resources",
        "dist": "public"
      }
    },
    "browserslist": [
      "extends @wordpress/browserslist-config"
    ],
    "engines": {
      "node": ">=16.0.0"
    },
    "scripts": {
      "dev": "bud dev",
      "build": "bud build",
      "lint": "npm run lint:js && npm run lint:css",
      "lint:js": "eslint resources/scripts",
      "lint:css": "stylelint \"resources/**/*.{css,scss,vue}\"",
      "test": "npm run lint"
    },
    "devDependencies": {
      "@babel/core": "^7.16.10",
      "@babel/plugin-proposal-class-properties": "^7.16.0",
      "@babel/plugin-proposal-object-rest-spread": "^7.16.0",
      "@babel/plugin-syntax-dynamic-import": "^7.8.3",
      "@babel/plugin-transform-runtime": "^7.16.4",
      "@babel/preset-env": "^7.16.4",
      "@roots/bud": "^5.2.0",
      "@roots/bud-postcss": "^5.2.0",
      "@roots/bud-prettier": "^5.2.0",
      "@roots/bud-sass": "^5.2.0",
      "@roots/bud-stylelint": "^5.2.0",
      "@roots/bud-tailwindcss": "^5.2.0",
      "@roots/sage": "^5.2.0",
      "@wordpress/browserslist-config": "^4.1.0",
      "babel-loader": "^8.2.3",
      "babel-plugin-add-module-exports": "^1.0.4",
      "eslint": "^8.6.0",
      "postcss": "^8.4.5",
      "postcss-import": "^14.0.2",
      "postcss-nested": "^5.0.6",
      "postcss-preset-env": "^7.1.0",
      "postcss-scss": "^4.0.3",
      "prettier": "^2.5.1",
      "react": "^17.0.2",
      "react-dom": "^17.0.2",
      "sass": "^1.45.2",
      "sass-loader": "^12.4.0",
      "stylelint": "^14.1.0",
      "stylelint-config-recommended-scss": "^5.0.2",
      "tailwindcss": "^3.0.8"
    }
  }

yarn manifest: 
  No manifest
```

### Configuration

```shell
/**
 * @typedef {import('@roots/bud').Bud} bud
 *
 * @param {bud} app
 */
module.exports = (app) =>
  app
    /**
     * Application entrypoints
     *
     * Paths are relative to your resources directory
     */
    .entry({
      app: ['scripts/app.js', 'styles/app.css'],
      editor: ['scripts/editor.js', 'styles/editor.css'],
    })

    /**
     * These files should be processed as part of the build
     * even if they are not explicitly imported in application assets.
     */
    .assets([app.path('src', 'images')])

    /**
     * These files will trigger a full page reload
     * when modified.
     */
    .watch([
      'tailwind.config.js',
      'resources/views/**/*.blade.php',
      'app/View/**/*.php',
    ])

    /**
     * Target URL to be proxied by the dev server.
     *
     * This is your local dev server.
     */
    .proxy('http://ifleetltd.loc');
```

### Relevant .budfiles

[bud.zip](https://github.com/roots/bud/files/8001587/bud.zip)

**Comment by mensch** [comment]
I had the same problem using the legacy version of Yarn (1.x is officially frozen). It took upgrading to [yarn berry](https://github.com/yarnpkg/berry) to get linking to work.

**Comment by kellymears** [comment]
you should remove most of your devDependencies.
 
i understand the docs are out of date since 5.2.0 and say to run `bud init`, but you don't need to do that. the release notes for v5.2.0 have more information.
 
 none of these are necessary:
 
 ```json
 {
      "@babel/core": "^7.16.10",
      "@babel/plugin-proposal-class-properties": "^7.16.0",
      "@babel/plugin-proposal-object-rest-spread": "^7.16.0",
      "@babel/plugin-syntax-dynamic-import": "^7.8.3",
      "@babel/plugin-transform-runtime": "^7.16.4",
      "@babel/preset-env": "^7.16.4",
      "babel-loader": "^8.2.3",
      "babel-plugin-add-module-exports": "^1.0.4",
      "eslint": "^8.6.0",
      "postcss": "^8.4.5",
      "postcss-import": "^14.0.2",
      "postcss-nested": "^5.0.6",
      "postcss-preset-env": "^7.1.0",
      "postcss-scss": "^4.0.3",
      "prettier": "^2.5.1",
      "sass": "^1.45.2",
      "sass-loader": "^12.4.0",
      "stylelint": "^14.1.0",
      "stylelint-config-recommended-scss": "^5.0.2"
}
```

the only thing you need in your manifest is what is listed here (and whatever your application requires in order for it to run):

https://github.com/roots/sage/blob/258d1f9675043108f7ecff0d4ed5586413a414e9/package.json#L24-L32
 
To add sass to that setup you run `yarn add @roots/bud-sass --dev`, write some sass, and keep on livin' your best life.

@qwp6t it's interesting that it won't resolve eslint in this case. probably worth trying to reproduce to see if the semver not aligning exactly is causing this issue. 

@sitesandsuch you might try pinning `eslint` at `8.6.0` (remove `^`), since bud wants a specific version here. but, i still think you should just remove it and let the framework manage it for you. we want to allow for this sort of freedom but i don't know that you want to volunteer as tribute.

**Comment by sitesandsuch** [comment]
@kellymears Thank you! Yes, I ran it with "bud install" as per (outdated) documentation. I started with a clean install again and only added bud-sass. Changed the entry files from  .css to .scss and... it works!!

BUT: I did upgrade yarn to yarn berry first. That is probably a good idea anyway, but I can no longer check if the above would have worked as well for yarn 1.x

**Comment by kellymears** [comment]
I think it does because we have e2e tests to cover npm and yarn 1. Glad you're sorted!

**Comment by evankford** [comment]
FYI For anyone finding this (I know it's closed), for me it was @babel/core that was creating the conflict!
