### ISSUE TITLE
Bug: Webpack parallelism

### ISSUE THREAD

**Issue by Pederytter** [roots/bud#1117]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Expected Behavior

Running yarn build on a dedicated server with 1 CPU should build the assets

### Actual Behavior

Getting following error:
`
    ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object 
    that does not match the API schema.
     - configuration[0].parallelism should be >= 1.
       -> The number of parallel processed modules in the compilation.
`

As far as I know it's because line 251 in this file is checking for how many CPU's the system have and takes one away:
https://github.com/roots/bud/blob/7c117f57c30b6106585986acee72737a2b92b005/sources/%40roots/bud/src/seed.ts

I tried to override this config, but not really sure how hooks work for this specific configuration. I tried the following:
`.hooks.on('build/parallelism', () => 1)`
But pretty sure I'm missing something.

### Steps To Reproduce

1. Have a server with just 1 CPU
2. yarn
3. yarn build

### version

@roots/bud/5.2.0

### What package manager are you using?

yarn classic

### version

1.22.17

### Are you using pnpm?

- [ ] yes
- [X] no

**Comment by kellymears** [comment]
```ts
bud.hooks.on('build.parallelism', () => 1)
```

apologies for the docs! you got it right.
