### ISSUE TITLE
add `@bud-bootstrap` extension

### ISSUE THREAD

**Issue by retlehs** [roots/bud#1142]
## feature request

add a `@bud-bootstrap` extension to help configure [bootstrap 5.x](https://getbootstrap.com/docs/5.1/getting-started/introduction/) with better support out of the box

ref https://discourse.roots.io/t/how-to-use-bootstrap-5-with-sage-10-beta-2/22259

**Comment by retlehs** [comment]
this likely just needs to be documented instead of handled with an extension since it's pretty straightforward 

[bootstrap docs](https://getbootstrap.com/docs/5.1/getting-started/webpack/#installing-bootstrap) recommend `@import "~bootstrap/scss/bootstrap";` which won't work with current bud

### using bud + bootstrap on a sage project

1. `yarn add bootstrap --dev`
1. `yarn add @roots/bud-sass --dev`
1. add `import 'bootstrap';` to `app.js`
1. rename `app.css` to `app.scss`
1. add `@import 'bootstrap/scss/...'` lines to `app.scss`

**Comment by kellymears** [comment]
@retlehs should this be documented in Sage docs?

**Comment by retlehs** [comment]
:+1: https://github.com/roots/docs/issues/328

**Comment by RaminEgh** [comment]
> 3\. import 'bootstrap';

Can you please extend and complete and explain your answer?

**Comment by retlehs** [comment]
@RaminEgh please [reference the docs](https://docs.roots.io/sage/10.x/css-frameworks/) or open a topic on https://discourse.roots.io/ for support
