### ISSUE TITLE
[bug] <a> elements that contain child nodes no longer observed by click interceptor

### ISSUE THREAD

**Issue by farmerpaul** [roots/bud#1149]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Expected Behavior

Clicking any link on a site that is proxied by `bud dev` dev server – whether the tag contains only a text node, or child nodes – should direct you to the corresponding target on the dev server, not take you to the page's original, non-proxied URL.

### Actual Behavior

If a link (`<a>` tag) contains a child node (such as `<svg>`, `<em>`, etc.), clicking that child node causes the dev server to bypass the link interceptor, taking you to the non-proxied version of the target URL.

### Steps To Reproduce

1. In a page on your dev instance, insert an `<a>` tag that takes you to another page of the site, and then insert a child element within that tag, such as `<em>`, that contains clickable content.
1. Run `bud dev` to load the corresponding page that contains that link.
1. Click the child element of that `<a>` tag.
1. You will be directed away from the dev server's proxied site, and to the original site instead.

It appears that [this line of code](https://github.com/roots/bud/blame/main/sources/%40roots/bud-server/src/client/proxy-click-interceptor.js#L25), introduced in Bud 5.1.0, is the culprit. The link interceptor now insists that the original DOM element that triggered the click, even if it's a child of the `<a>` element, must be an `<a>` element itself, and exits the function.

### version

@roots/bud/5.3.2 wsl-x64 node-v16.13.2

### What package manager are you using?

yarn classic

### version

1.22.17

### Are you using pnpm?

- [ ] yes
- [X] no

**Comment by kellymears** [comment]
thanks for the report!

for now, if you want, you can pretty much just copy/paste that script and modify as needed. i don't think there is any harm in it running more than once and although it's transpiled it doesn't seem like it changes it appreciably.

**Comment by kellymears** [comment]
@farmerpaul this [should be fixed in 5.4.0](https://github.com/roots/bud/releases/tag/v5.4.0). 

There is more that could be improved to keep the dev server "sticky" (in bud and acorn) but that can be handled in other issues. Closing 🎉
