### ISSUE TITLE
How to achieve glob import for style files?

### ISSUE THREAD

**Issue by SergiOnGit** [roots/bud#1197]
Importing style files one by one is very annoying. Is there a way to import whole folder? In a previous version I was using https://github.com/soluml/glob-import-loader but I can't make it work here. Can you help?

**Comment by kellymears** [comment]
bud has many ways to handle imports. 

1. you should [read the docs](https://bud.js.org/docs/bud.entry)
2. you should [ask for help on the roots discourse](https://discourse.roots.io).
3. having done those things, if there is an issue with this software (lord knows) you should reformulate your question and use the issue template.
