### ISSUE TITLE
Document: bud.serve when using a VM

### ISSUE THREAD

**Issue by cspicuzza** [roots/bud#1215]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Expected Behavior

For the site to load when using the dev url

### Actual Behavior

Chrome gives the following error:

```
This site can’t be reached
example.test refused to connect.
```

Bud shows the following:
![url is in red](https://user-images.githubusercontent.com/4442172/156695167-d58f43a5-b03d-45be-a021-1f6f2b538f70.png)

### Steps To Reproduce

1. Start a fresh workspace using the latest Roots stack
2. Make no configuration changes
3. Install all dependencies
4. `yarn dev`
5. Visit http://example.test:3000

### version

5.4.0

### What package manager are you using?

yarn classic

### version

1.22.17

### Are you using pnpm?

- [ ] yes
- [X] no

### Configuration

```zsh
/**
 * @typedef {import('@roots/bud').Bud} bud
 *
 * @param {bud} app
 */
module.exports = async (app) => {
  app
    /**
     * Application entrypoints
     *
     * Paths are relative to your resources directory
     */
    .entry({
      app: ['@scripts/app', '@styles/app'],
      editor: ['@scripts/editor', '@styles/editor'],
    })

    /**
     * These files should be processed as part of the build
     * even if they are not explicitly imported in application assets.
     */
    .assets('images')

    /**
     * These files will trigger a full page reload
     * when modified.
     */
    .watch([
      'tailwind.config.js',
      'resources/views/**/*.blade.php',
      'app/View/**/*.php',
    ])

    /**
     * Target URL to be proxied by the dev server.
     *
     * This is your local dev server.
     */
    .proxy('http://example.test')

    /**
     * Development URL
     */
    .serve('http://example.test:3000');
};
```

### Relevant .budfiles

[budfiles.zip](https://github.com/roots/bud/files/8182879/budfiles.zip)

**Comment by kellymears** [comment]
I'm not sure what's going on here. I can't reproduce it and because this is an issue with the server the budfiles don't help at all. What is your development setup like? do you use docker, trellis, valet? Have you tried a different port?

bud 5.5.0 is about to release which includes a pretty major reworking of the server in general: https://github.com/roots/bud/pull/1069.

I think the next step is for you to try that (once its out) and then we can go from there.

**Comment by cspicuzza** [comment]
My test was done using the entire Roots stack: Trellis/Bedrock/Sage (all latest). I tried using port 8000 with the same result.

**Comment by retlehs** [comment]
> Make no configuration changes

@cspicuzza since you're using a VM, you'll want to drop `.serve('http://example.test:3000/');` from your bud config

this is really just a docs issue right now and not a bug with bud itself

**Comment by cspicuzza** [comment]
@retlehs I'll close this ticket then.  I tried `.serve()` because of [this issue](roots/docs#383).

**Comment by retlehs** [comment]
@cspicuzza no worries! i'll keep this open for visibility until docs are updated :+1:
