### ISSUE TITLE
[bug] Using Tailwind directives in sass results in `scss/at-rule-no-unknown`

### ISSUE THREAD

**Issue by joshuafredrickson** [roots/bud#1226]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Expected Behavior

Successful builds when using Tailwind and Sass in the following configuration:

```json
"@roots/bud": "5.5.0",
"@roots/bud-sass": "5.5.0",
"@roots/bud-stylelint": "5.5.0",
"@roots/bud-tailwindcss": "5.5.0",
"@roots/sage": "5.5.0",
```

### Actual Behavior

The build fails with the following error:

```
✖  Unexpected unknown at-rule "@screen"  scss/at-rule-no-unknown 
```

This is because [stylelint-config-recommend-scss](https://github.com/stylelint-scss/stylelint-config-recommended-scss/blob/master/index.js), which is included via @roots/bud-sass, requires a prefix on `at-rule-no-unknown` in order to apply the rule to scss files (e.g., `scss/at-rule-no-unknown`).

Because @roots/bud-tailwindcss doesn't include this prefix for `at-rule-no-unknown`, all Tailwind directives in scss files fail to build.

The following `.stylelintrc` works as expected:

```json
{
  "extends": [
    "@roots/bud-sass/stylelint-config",
    "@roots/sage/stylelint-config",
    "@roots/bud-tailwindcss/stylelint-config"
  ],
  "rules": {
    "scss/at-rule-no-unknown": [
      true,
      {
        "ignoreAtRules": [
          "extend",
          "at-root",
          "debug",
          "warn",
          "error",
          "if",
          "else",
          "for",
          "each",
          "while",
          "mixin",
          "include",
          "content",
          "return",
          "tailwind",
          "apply",
          "responsive",
          "variants",
          "screen",
          "function",
          "use",
          "forward",
          "layer"
        ]
      }
    ]
  }
}
```

Unfortunately, we can't just add an additional rule in bud-tailwind's stylelint-config as it would fail for those who aren't using bud-sass. Would it make sense to add an additional config like `@roots/bud-tailwindcss/stylelint-config/sass`? 

### Steps To Reproduce

1. Add @roots/bud-tailwind, @roots/bud-sass and @roots/bud-stylelint to a project.
1. Create an scss file containing a Tailwind-specific @ rule like `@screen {}`. 
1. `yarn build`

### version

5.5.0

### What package manager are you using?

yarn classic

### version

1.22.17

### Are you using pnpm?

- [ ] yes
- [X] no

**Comment by kellymears** [comment]
@joshuafredrickson i'm thinking

`stylelint-config/rules/at-rule-no-unknown.js`:

```js
/**
 * at-rule-no-unknown
 *
 * @see {@link https://github.com/roots/bud/issues/1226}
 */
module.exports = [
  true,
  {
    ignoreAtRules: [
      'extend',
      'at-root',
      'debug',
      'warn',
      'error',
      'if',
      'else',
      'for',
      'each',
      'while',
      'mixin',
      'include',
      'content',
      'return',
      'tailwind',
      'apply',
      'responsive',
      'variants',
      'screen',
      'function',
      'use',
      'forward',
      'layer',
    ],
  },
]
```

`stylelint-config/base.js`:

```js
module.exports = {
  rules: {
    'function-no-unknown': [
      true,
      {
        ignoreFunctions: ['theme'],
      },
    ],
  },
}
```

`stylelint-config/index.js`:

```js
module.exports = {
  rules: {
    ...require('./base'),
    'at-rule-no-unknown': require('./rules/at-rule-no-unknown'),
  },
}
```

`stylelint-config/scss/index.js`:

```js
// stylelint-config/scss/index.js
module.exports = {
  rules: {
    ...require('../base'),
    'scss/at-rule-no-unknown': require('../rules/at-rule-no-unknown'),
  },
}
```

Make sense?

**Comment by joshuafredrickson** [comment]
It does! 

Does it matter that the default config would now be ignoring Tailwind directives as well? If so, we could strip those out of the default config and apply the same sort of logic to the Tailwind stylelint. We'd be maintaining two sets of at-rule-no-unknown, but I think we are as it is already.

Let me know if you want me to put together a PR for this.

**Comment by retlehs** [comment]
rolling out into v5.7.3 right now, thank you!
