### ISSUE TITLE
[bug] Unable to set PostCSS plugins in 5.6.2

### ISSUE THREAD

**Issue by mensch** [roots/bud#1249]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Expected Behavior

I've been running Bud at 5.5.* with a PostCSS plugin configured, the build process completed successfully including the transformations offered by the plugin.

### Actual Behavior

Bud 5.6.2 seems to break my current configuration, the build process hangs on this error: `TypeError: app.entry(...).assets(...).watch(...).proxy(...).serve(...).postcss.setPlugins(...).use is not a function`

### Steps To Reproduce

1. Add `postcss.setPlugins` to bud.config.js
2. Run `yarn build`

### version

5.6.2

### What package manager are you using?

yarn berry

### version

3.2.0

### Are you using pnpm?

- [ ] yes
- [X] no

### Logs

```zsh
TypeError: app.entry(...).assets(...).watch(...).proxy(...).serve(...).postcss.setPlugins(...).use is not a function
```

### Configuration

```zsh
const SVGSpritemapPlugin = require('svg-spritemap-webpack-plugin');

/**
 * @typedef {import('@roots/bud').Bud} bud
 *
 * @param {bud} app
 */
module.exports = async (app) =>
  app
    /**
     * Application entrypoints
     *
     * Paths are relative to your resources directory
     */
    .entry({
      app: ['@scripts/app', '@styles/app'],
      editor: ['@scripts/editor', '@styles/editor'],
    })

    /**
     * These files should be processed as part of the build
     * even if they are not explicitly imported in application assets.
     */
    .assets('images')

    /**
     * These files will trigger a full page reload
     * when modified.
     */
    .watch(['resources/views/**/*.blade.php', 'app/View/**/*.php'])

    /**
     * Target URL to be proxied by the dev server.
     *
     * This is your local dev server.
     */
    .proxy('http://website.test')

    /**
      * Development URL
      */
    .serve('http://localhost:3000')

    /**
     * Add PostCSS plugins
     */
    .postcss.setPlugins({
      'postcss-pxtorem': require.resolve('postcss-pxtorem'),
    })

    /**
     * Generate SVG sprite based on available icons
     */
    .use(
      new SVGSpritemapPlugin('resources/images/icons/*.svg', {
        output: {
          filename: 'icons.svg',
          chunk: {keep: true},
          svgo: false,
        },
        sprite: {
          prefix: false,
        },
      }),
    );
```

**Comment by kellymears** [comment]
Hey @mensch I actually don't think this is a bug. 

`bud.postcss.x` methods don't return the `bud` instance. they return `bud.postcss`. 

`bud.postcss.use` is not a function, which is why it's throwing.

you can use [bud.tap](https://bud.js.org/docs/bud.tap) so you can keep the function chain alive:

```ts
     /**
      * Development URL
      */
    .serve('http://localhost:3000')

    /**
     * Add PostCSS plugins
     */
    .tap(({postcss}) => postcss.setPlugins({ 'postcss-pxtorem': require.resolve('postcss-pxtorem')}))

    /**
     * Generate SVG sprite based on available icons
     */
    .use(
      new SVGSpritemapPlugin('resources/images/icons/*.svg', {
        output: {
          filename: 'icons.svg',
          chunk: {keep: true},
          svgo: false,
        },
        sprite: {
          prefix: false,
        },
      }),
    );
```

Also, [bud.postcss.setPlugins](https://bud.js.org/extensions/bud-postcss#postcsssetplugins) will completely overwrite the entire plugins object with whatever is supplied. It's hard to tell but you might want to use [bud.postcss.setPlugin](https://bud.js.org/extensions/bud-postcss#postcsssetplugin) instead:

```ts
bud.postcss.setPlugin('postcss-pxtorem', require.resolve('postcss-pxtorem'))
```

**Comment by mensch** [comment]
Ah yes, that makes sense. I tried shifting the function higher up in the chain, but that didn't seem to have any effect.

Using `tap` fixes the issue and I see that [there's documentation on it](https://bud.js.org/docs/bud.tap) I've missed previously.
