### ISSUE TITLE
Please anyone can show me how to setup Vue.js to Sage Wordpress Theme using `bud.js` 🙏

### ISSUE THREAD

**Issue by muhghazaliakbar** [roots/bud#1281]
I have been here all days to setup the Vue.js to the Theme, but still not working. Please anyone can provide me an example theme setup with Vue.js? I'll really appreciate 🙏

**Comment by retlehs** [comment]
hey @muhghazaliakbar, we actually just use github issues for bug reports. please post over on https://discourse.roots.io/ to get support
