### ISSUE TITLE
Can't terminate `bud dev` process with cmd/ctrl C

### ISSUE THREAD

**Issue by 970DesignUser** [roots/bud#1292]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Expected Behavior

There should be a way to stop a currently running `bud dev` process.  Or there should be documentation for how to stop this process if such a method exists.

### Actual Behavior

Once `bud dev` is running you can stop it with `Q`, but ctrl/cmd+c are not working

### Steps To Reproduce

1. Run `bud dev`
2. Attempt to stop process via ctrl+c
3. Process does not terminate

**Comment by 970DesignUser** [comment]
Just for documentation..  `q` will terminate the process.

Would be great if this were added to the docs for `bud dev` though!

**Comment by retlehs** [comment]
we'll get cmd/ctrl c support added back, thanks for the report

**Comment by retlehs** [comment]
this is working again as of bud 5.7.x
