### ISSUE TITLE
[bug] [docs] `bud install / bud init is deprecated`

### ISSUE THREAD

**Issue by strarsis** [roots/bud#1346]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Expected Behavior

When following the instructions for installing and using a `bud` extension (like [`@roots/bud-imagemin`](https://github.com/roots/bud/tree/v5.7.7/sources/@roots/bud-imagemin)), no deprecation warnings should be caused (as a command isn't needed/used anymore).

### Actual Behavior

The documentation (as for [`@roots/bud-imagemin`](https://github.com/roots/bud/tree/v5.7.7/sources/@roots/bud-imagemin)) instructs [to invoke `bud init`](https://github.com/roots/bud/tree/v5.7.7/sources/@roots/bud-imagemin#:~:text=bud-imagemin%20--dev-,run%20bud%20init,-after%20installation%20to) after installing the bud extension package.
However, using the `bud init` command results in a deprecation warning as the command isn't needed and shouldn't be used anymore:
````
bud install / bud init is deprecated
This command was deprecated in 5.3.0. In the future this command will throw an error.
````

### Steps To Reproduce

1. Follow the instructions for installing the [`@roots/bud-imagemin`](https://github.com/roots/bud/tree/v5.7.7/sources/@roots/bud-imagemin) extension.
Note that the `bud init` invoking step causes a deprecation warning.

### version

5.7.7

### What package manager are you using?

yarn classic

### version

1.22.18

### Are you using pnpm?

- [ ] yes
- [X] no

### Logs

```zsh
yarn bud init
yarn run v1.22.18
$ [...]/node_modules/.bin/bud init
bud install / bud init is deprecated
This command was deprecated in 5.3.0. In the future this command will throw an error.
Done in 1.15s.
```

### Configuration

Using the original [`bud.config.js` of latest main (Sage 10) branch](https://github.com/roots/sage/blob/82ad056fae9af21004cc711fa79d3826c61d93c3/bud.config.js) (at time of writing).

**Comment by kellymears** [comment]
addressed in https://github.com/roots/bud/pull/1337/commits/320c2a98e41623d6229b92bf57438c8fd4ce3f8c
