### ISSUE TITLE
Feature request: ACME client for proxy SSL certs

### ISSUE THREAD

**Issue by strarsis** [roots/bud#1347]
I already use a local CA server for letting HTTPS servers (`nginx`; ...) sign certificates ([`smallstep step-ca`](https://github.com/smallstep/certificates)) over the ACME protocol.

It would be great if the same CA could be used by the `bud` proxy, then the certificate used for the proxy HTTPS connection would be valid (as the local CA server is already trusted by all the development devices), avoiding the browser warning.

**Comment by kellymears** [comment]
You can use [NODE_EXTRA_CA_CERTS=file](https://nodejs.org/api/cli.html#node_extra_ca_certsfile) to add your CA. I don't think it's possible for bud to do this on your behalf because:

> The NODE_EXTRA_CA_CERTS environment variable is only read when the Node.js process is first launched. Changing the value at runtime using process.env.NODE_EXTRA_CA_CERTS has no effect on the current process.

**Comment by kellymears** [comment]
i'm marking this as closed but let me know if you find that bud needs to do something to accommodate.

**Comment by vincent-lu** [comment]
hey @kellymears I'm hoping you can point me to the right direction, I'm trying to run `bud.serve` with the following arguments:

```
.serve('https://mydev.test:3000', {
  cert: '/path-to/mydev.test.crt',
  key: '/path-to/mydev.test.key',
});
```

The same crt & key works with nginx config.

But when I run `export NODE_EXTRA_CA_CERTS=/path-to/ca.crt && yarn dev` and open `https://mydev.test:3000/`, I still get "This site can’t provide a secure connection mydev.test uses an unsupported protocol. ERR_SSL_VERSION_OR_CIPHER_MISMATCH"

What am I doing wrong here?
