### ISSUE TITLE
GitHub Action for releases: Submit PR's to Sage for bumping Bud versions

### ISSUE THREAD

**Issue by retlehs** [roots/bud#1408]

**Comment by kellymears** [comment]
Should we just set up renovate for @roots/sage?

**Comment by retlehs** [comment]
i haven't messed with renovate's grouped deps updates, but if it does what we need then that's fine with me :+1: 

@QWp6t what do you think?

**Comment by retlehs** [comment]
thank you @kellymears 🙏  roots/sage#3060
