### ISSUE TITLE
Version 5.8.3 of bud-sass breaks the build process in the Roots/Sage theme

### ISSUE THREAD

**Issue by 100wunder** [roots/bud#1415]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Expected Behavior

yarn build should be successful. 

### Actual Behavior

`yarn build --log` breaks with **Error: name is a required property for extensions**

**Workaround:**
Set fixed version 5.6.2 for bud-sass in the package.json of the Sage theme.

### Steps To Reproduce

1. Install most recent Roots/Sage theme 
2. run yarn build

### version

5.6.2

### What package manager are you using?

yarn classic

### version

1.22.18

### Are you using pnpm?

- [ ] yes
- [ ] no

**Comment by kellymears** [comment]
This isn't a bug, per se; your dependencies are just out of sync. It's definitely something to improve in the `@roots/sage` DX. 

bud extensions @5.8.x will not work with `@roots/bud@5.7.x`. Sage is at 5.7.7. The solution is to make sure all the extensions are synced:

```json
  "devDependencies": {
    "@roots/bud": "5.8.3",
    "@roots/bud-sass": "5.8.3",
    "@roots/bud-tailwindcss": "5.8.3",
    "@roots/sage": "5.8.3"
  },
  ```
  
  Or, install the extension with a matching version if there is some blocker there: `yarn add @roots/bud-sass@5.7.7`.

**Comment by bekahmcdonald** [comment]
I was getting the following error, and making sure my `bud` and `bud-sass` dependencies were the same version number is the only thing that fixed it.

```bash
Error importing @roots/bud-sass
 Error [ERR_REQUIRE_ESM]: require() of ES Module [secure]/node_modules/@roots/bud-sass/lib/index.js from [secure]/node_modules/@roots/bud-extensions/lib/cjs/Extensions/extensions.service.js not supported.
Instead change the require of index.js in [secure]/node_modules/@roots/bud-extensions/lib/cjs/Extensions/extensions.service.js to a dynamic import() which is available in all CommonJS modules.
```

Sharing because I was googling my error for ages and finding nothing useful. Hopefully this will help others experiencing the same problem!
