### ISSUE TITLE
Minor syntax issue in PostCSS docs

### ISSUE THREAD

**Issue by tedw** [roots/bud#1457]
Just noticed a minor syntax issue in the [PostCSS docs](https://bud.js.org/extensions/bud-postcss/#postcsssetplugins):

```js
bud.postcss.setPlugins(new Map([
  ['postcss-import', require.resolve('postcss-import')],
  // The second opening square bracket here isn’t closed
  ['postcss-preset-env', [
    require.resolve('postcss-preset-env'),
    {stage: 1},
  ],
])// Also missing a closing paren here
```

Source: https://github.com/roots/bud/blob/main/sources/%40repo/docs/content/extensions/bud-postcss.mdx

**Comment by kellymears** [comment]
Thanks for the report
