### ISSUE TITLE
[bug] yarn dev stuck at emitting 95%

### ISSUE THREAD

**Issue by sincerite** [roots/bud#1464]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Expected Behavior

Emit chunks correctly.

### Actual Behavior

Stuck at emitting 95%

If I comment out any of entry lines, everything starts working correctly (one more line causes this bug).

### Steps To Reproduce

1. Have too many entries
2. Run yarn dev

### version

5.8.7

### What package manager are you using?

yarn classic

### version

1.22.18

### Are you using pnpm?

- [ ] yes
- [X] no

### Logs

```zsh
[bud@5.8.7] [bud] › ✔  booted extensions
[bud@5.8.7] [bud] › ❯  process.env.NODE_ENV: development
[bud@5.8.7] [bud] › ❯  process.env.BABEL_ENV: development
[bud@5.8.7] [bud] › ❯  facade added to queue: entry [{"app":["scripts/app.ts","styles/app.scss"],"hero":["styles/blocks/hero.scss"],"call-to-action":["style                                                                                                                          s/blocks/call-to-action.scss"],"case-studies":["styles/blocks/case-studies.scss"],"case-studies-grid":["styles/blocks/case-studies-grid.scss"],"case-study-c                                                                                                                          arousel":["styles/blocks/case-study-carousel.scss"],"contact-form":["styles/blocks/contact-form.scss"],"faq":["styles/blocks/faq.scss"],"features":["styles/                                                                                                                          blocks/features.scss"],"features-carousel":["styles/blocks/features-carousel.scss"],"map":["styles/blocks/map.scss"],"photo-with-description":["styles/block                                                                                                                          s/photo-with-description.scss"],"programmer-quotes":["styles/blocks/programmer-quotes.scss"],"project-phases":["styles/blocks/project-phases.scss"],"recent-                                                                                                                          posts":["styles/blocks/recent-posts.scss"],"bogo":"styles/blocks/bogo.scss","services":["styles/blocks/services.scss"],"testimonials":["styles/blocks/testim                                                                                                                          onials.scss"],"web-apps":["styles/blocks/web-apps.scss"],"benefits":["styles/blocks/benefits.scss"],"editor":["styles/editor.scss"],"vendor":["styles/vendor                                                                                                                          .scss"]}]
[bud@5.8.7] [bud] › ❯  facade added to queue: assets [[["[secure]/resources/images","[secure]/public"]]]
[bud@5.8.7] [bud] › ❯  facade added to queue: minimize [false]
[bud@5.8.7] [bud] › ❯  facade added to queue: hash [false]
[bud@5.8.7] [bud] › ❯  facade added to queue: provide [{"jquery":["jQuery","$"]}]
[bud@5.8.7] [bud] › ❯  facade added to queue: devtool ["inline-cheap-module-source-map"]
[bud@5.8.7] [bud] › ❯  facade added to queue: watch ["resources/views/**/*","app/**/*"]
[bud@5.8.7] [bud] › ❯  facade added to queue: proxy ["http://weastronauts-www.lndo.site/"]
[bud@5.8.7] [bud] › ❯  executing entry [{"app":["scripts/app.ts","styles/app.scss"],"hero":["styles/blocks/hero.scss"],"call-to-action":["styles/blocks/call                                                                                                                          -to-action.scss"],"case-studies":["styles/blocks/case-studies.scss"],"case-studies-grid":["styles/blocks/case-studies-grid.scss"],"case-study-carousel":["st                                                                                                                          yles/blocks/case-study-carousel.scss"],"contact-form":["styles/blocks/contact-form.scss"],"faq":["styles/blocks/faq.scss"],"features":["styles/blocks/featur                                                                                                                          es.scss"],"features-carousel":["styles/blocks/features-carousel.scss"],"map":["styles/blocks/map.scss"],"photo-with-description":["styles/blocks/photo-with-                                                                                                                          description.scss"],"programmer-quotes":["styles/blocks/programmer-quotes.scss"],"project-phases":["styles/blocks/project-phases.scss"],"recent-posts":["styl                                                                                                                          es/blocks/recent-posts.scss"],"bogo":"styles/blocks/bogo.scss","services":["styles/blocks/services.scss"],"testimonials":["styles/blocks/testimonials.scss"]                                                                                                                          ,"web-apps":["styles/blocks/web-apps.scss"],"benefits":["styles/blocks/benefits.scss"],"editor":["styles/editor.scss"],"vendor":["styles/vendor.scss"]}]
[bud@5.8.7] [bud] › ❯  executing assets [[["[secure]/resources/images","[secure]/public"]]]
[bud@5.8.7] [bud] › ❯  executing minimize [false]
[bud@5.8.7] [bud] › ❯  executing hash [false]
[bud@5.8.7] [bud] › ✔  file hashing disabled
[bud@5.8.7] [bud] › ❯  executing provide [{"jquery":["jQuery","$"]}]
[bud@5.8.7] [bud] › ❯  executing devtool ["inline-cheap-module-source-map"]
[bud@5.8.7] [bud] › ❯  devtool set: inline-cheap-module-source-map
[bud@5.8.7] [bud] › ❯  executing watch ["resources/views/**/*","app/**/*"]
[bud@5.8.7] [bud] › ❯  executing proxy ["http://weastronauts-www.lndo.site/"]
[bud@5.8.7] [bud] › ❯  executing run none
[bud@5.8.7] [bud] › ✔  write profile [secure]/.budfiles/bud/profile.json
[bud@5.8.7] [bud] › ✔  write profile [secure]/.budfiles/bud/profile.json
[proxy] › ❯  autoRewrite true
[proxy] › ❯  changeOrigin true
[proxy] › ❯  cookieDomainRewrite 0.0.0.0:3000
[proxy] › ❯  followRedirects false
[proxy] › ❯  hostRewrite 0.0.0.0:3000
[proxy] › ❯  logLevel info
[proxy] › ❯  logProvider [Function: logProvider]
[proxy] › ❯  onProxyReq [Function: bound _interceptor] AsyncFunction
[proxy] › ❯  onProxyRes [AsyncFunction: proxyRes]
[proxy] › ❯  protocolRewrite null
[proxy] › ❯  secure false
[proxy] › ❯  selfHandleResponse true
[proxy] › ❯  target URL {
  href: 'http://weastronauts-www.lndo.site/',
  origin: 'http://weastronauts-www.lndo.site',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'weastronauts-www.lndo.site',
  hostname: 'weastronauts-www.lndo.site',
  port: '',
  pathname: '/',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
[bud@5.8.7] [bud] › ✖  Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1508:7)
    at Http.listen ([secure]/node_modules/@roots/bud-server/lib/cjs/server/server.base.js:47:14)
    at Server.run ([secure]/node_modules/@roots/bud-server/lib/cjs/server/index.js:144:31)
    at async Bud.run ([secure]/node_modules/@roots/bud-api/lib/cjs/methods/run/index.js:14:29)
    at async Api.call ([secure]/node_modules/@roots/bud-api/lib/cjs/api/api.service.js:104:16)
    at async DevCommand.run ([secure]/node_modules/@roots/bud/lib/cjs/cli/commands/base.js:86:9)
    at async DevCommand.execute ([secure]/node_modules/@roots/bud/lib/cjs/cli/commands/build.js:298:9)
⠋ 10% building
⠹ 29% building
⠇ 29% building

warn - You have enabled the JIT engine which is currently in preview.
⠋ 95% emitting
```

### Configuration

```zsh
module.exports = async (app) =>
	app
		/**
		 * Application entrypoints
		 *
		 * Paths are relative to your resources directory2
		 */
		.entry({
			app: ['scripts/app.ts', 'styles/app.scss'],
			hero: ['styles/blocks/hero.scss'],
			"call-to-action": ['styles/blocks/call-to-action.scss'],
			"case-studies": ['styles/blocks/case-studies.scss'],
			"case-studies-grid": ['styles/blocks/case-studies-grid.scss'],
			"case-study-carousel": ['styles/blocks/case-study-carousel.scss'],
			"contact-form": ['styles/blocks/contact-form.scss'],
			"faq": ['styles/blocks/faq.scss'],
			"features": ['styles/blocks/features.scss'],
			"features-carousel": ['styles/blocks/features-carousel.scss'],
			"map": ['styles/blocks/map.scss'],
			"photo-with-description": ['styles/blocks/photo-with-description.scss'],
			"programmer-quotes": ['styles/blocks/programmer-quotes.scss'],
			"project-phases": ['styles/blocks/project-phases.scss'],
			"recent-posts": ['styles/blocks/recent-posts.scss'],
			"bogo": 'styles/blocks/bogo.scss',
			"services": ['styles/blocks/services.scss'],
			"testimonials": ['styles/blocks/testimonials.scss'],
			"web-apps": ['styles/blocks/web-apps.scss'],
			"benefits": ['styles/blocks/benefits.scss'],
			editor: ['styles/editor.scss'],
			vendor: ['styles/vendor.scss']
		})

		/**
		 * These files should be processed as part of the build
		 * even if they are not explicitly imported in application assets.
		 */
		.assets([
			[app.path('resources/images'), app.path('public')]
		])
		.minimize(false)
		.hash(false)


		// .alias("images", app.path('@src/resources/images'))

		.provide({ jquery: ["jQuery", "$"], })

		.devtool('inline-cheap-module-source-map')

		/**
		 * These files will trigger a full page reload
		 * when modified.
		 */
		.watch('resources/views/**/*', 'app/**/*')

		.hooks.on("build.optimization.runtimeChunk", "single")

		/**
		 * Target URL to be proxied by the dev server.
		 *
		 * This is your local dev server.
		 */
		.proxy(new URL('http://weastronauts-www.lndo.site'));
```

### Relevant .budfiles

module.exports = {
  "entry": {
    "app": {
      "import": [
        "@roots/bud-server/client/index.js?name=bud&bud.overlay=true&bud.indicator=true&path=/__bud/hmr",
        "@roots/bud-server/client/proxy-click-interceptor.js",
        "scripts/app.ts",
        "styles/app.scss"
      ]
    },
    "hero": {
      "import": [
        "@roots/bud-server/client/index.js?name=bud&bud.overlay=true&bud.indicator=true&path=/__bud/hmr",
        "@roots/bud-server/client/proxy-click-interceptor.js",
        "styles/blocks/hero.scss"
      ]
    },
    "call-to-action": {
      "import": [
        "@roots/bud-server/client/index.js?name=bud&bud.overlay=true&bud.indicator=true&path=/__bud/hmr",
        "@roots/bud-server/client/proxy-click-interceptor.js",
        "styles/blocks/call-to-action.scss"
      ]
    },
    "case-studies": {
      "import": [
        "@roots/bud-server/client/index.js?name=bud&bud.overlay=true&bud.indicator=true&path=/__bud/hmr",
        "@roots/bud-server/client/proxy-click-interceptor.js",
        "styles/blocks/case-studies.scss"
      ]
    },
    "case-studies-grid": {
      "import": [
        "@roots/bud-server/client/index.js?name=bud&bud.overlay=true&bud.indicator=true&path=/__bud/hmr",
        "@roots/bud-server/client/proxy-click-interceptor.js",
        "styles/blocks/case-studies-grid.scss"
      ]
    },
    "case-study-carousel": {
      "import": [
        "@roots/bud-server/client/index.js?name=bud&bud.overlay=true&bud.indicator=true&path=/__bud/hmr",
        "@roots/bud-server/client/proxy-click-interceptor.js",
        "styles/blocks/case-study-carousel.scss"
      ]
    },
    "contact-form": {
      "import": [
        "@roots/bud-server/client/index.js?name=bud&bud.overlay=true&bud.indicator=true&path=/__bud/hmr",
        "@roots/bud-server/client/proxy-click-interceptor.js",
        "styles/blocks/contact-form.scss"
      ]
    },
    "faq": {
      "import": [
        "@roots/bud-server/client/index.js?name=bud&bud.overlay=true&bud.indicator=true&path=/__bud/hmr",
        "@roots/bud-server/client/proxy-click-interceptor.js",
        "styles/blocks/faq.scss"
      ]
    },
    "features": {
      "import": [
        "@roots/bud-server/client/index.js?name=bud&bud.overlay=true&bud.indicator=true&path=/__bud/hmr",
        "@roots/bud-server/client/proxy-click-interceptor.js",
        "styles/blocks/features.scss"
      ]
    },
    "features-carousel": {
      "import": [
        "@roots/bud-server/client/index.js?name=bud&bud.overlay=true&bud.indicator=true&path=/__bud/hmr",
        "@roots/bud-server/client/proxy-click-interceptor.js",
        "styles/blocks/features-carousel.scss"
      ]
    },
    "map": {
      "import": [
        "@roots/bud-server/client/index.js?name=bud&bud.overlay=true&bud.indicator=true&path=/__bud/hmr",
        "@roots/bud-server/client/proxy-click-interceptor.js",
        "styles/blocks/map.scss"
      ]
    },
    "photo-with-description": {
      "import": [
        "@roots/bud-server/client/index.js?name=bud&bud.overlay=true&bud.indicator=true&path=/__bud/hmr",
        "@roots/bud-server/client/proxy-click-interceptor.js",
        "styles/blocks/photo-with-description.scss"
      ]
    },
    "programmer-quotes": {
      "import": [
        "@roots/bud-server/client/index.js?name=bud&bud.overlay=true&bud.indicator=true&path=/__bud/hmr",
        "@roots/bud-server/client/proxy-click-interceptor.js",
        "styles/blocks/programmer-quotes.scss"
      ]
    },
    "project-phases": {
      "import": [
        "@roots/bud-server/client/index.js?name=bud&bud.overlay=true&bud.indicator=true&path=/__bud/hmr",
        "@roots/bud-server/client/proxy-click-interceptor.js",
        "styles/blocks/project-phases.scss"
      ]
    },
    "recent-posts": {
      "import": [
        "@roots/bud-server/client/index.js?name=bud&bud.overlay=true&bud.indicator=true&path=/__bud/hmr",
        "@roots/bud-server/client/proxy-click-interceptor.js",
        "styles/blocks/recent-posts.scss"
      ]
    },
    "bogo": {
      "import": [
        "@roots/bud-server/client/index.js?name=bud&bud.overlay=true&bud.indicator=true&path=/__bud/hmr",
        "@roots/bud-server/client/proxy-click-interceptor.js",
        "styles/blocks/bogo.scss"
      ]
    },
    "services": {
      "import": [
        "@roots/bud-server/client/index.js?name=bud&bud.overlay=true&bud.indicator=true&path=/__bud/hmr",
        "@roots/bud-server/client/proxy-click-interceptor.js",
        "styles/blocks/services.scss"
      ]
    },
    "testimonials": {
      "import": [
        "@roots/bud-server/client/index.js?name=bud&bud.overlay=true&bud.indicator=true&path=/__bud/hmr",
        "@roots/bud-server/client/proxy-click-interceptor.js",
        "styles/blocks/testimonials.scss"
      ]
    },
    "web-apps": {
      "import": [
        "@roots/bud-server/client/index.js?name=bud&bud.overlay=true&bud.indicator=true&path=/__bud/hmr",
        "@roots/bud-server/client/proxy-click-interceptor.js",
        "styles/blocks/web-apps.scss"
      ]
    },
    "benefits": {
      "import": [
        "@roots/bud-server/client/index.js?name=bud&bud.overlay=true&bud.indicator=true&path=/__bud/hmr",
        "@roots/bud-server/client/proxy-click-interceptor.js",
        "styles/blocks/benefits.scss"
      ]
    },
    "editor": {
      "import": [
        "@roots/bud-server/client/index.js?name=bud&bud.overlay=true&bud.indicator=true&path=/__bud/hmr",
        "@roots/bud-server/client/proxy-click-interceptor.js",
        "styles/editor.scss"
      ]
    },
    "vendor": {
      "import": [
        "@roots/bud-server/client/index.js?name=bud&bud.overlay=true&bud.indicator=true&path=/__bud/hmr",
        "@roots/bud-server/client/proxy-click-interceptor.js",
        "styles/vendor.scss"
      ]
    }
  },
  "bail": false,
  "cache": {
    "name": "bud.development",
    "type": "filesystem",
    "version": "_gz4gzgmpguenydpsrvgd3b_sbu_",
    "cacheDirectory": "/srv/weastronauts/web/app/themes/weastronauts-theme/.budfiles/cache/webpack",
    "managedPaths": [
      "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules"
    ],
    "buildDependencies": {
      "bud": [
        "/srv/weastronauts/web/app/themes/weastronauts-theme/package.json",
        "/srv/weastronauts/web/app/themes/weastronauts-theme/.editorconfig",
        "/srv/weastronauts/web/app/themes/weastronauts-theme/.eslintrc.js",
        "/srv/weastronauts/web/app/themes/weastronauts-theme/.prettierrc",
        "/srv/weastronauts/web/app/themes/weastronauts-theme/.stylelintrc",
        "/srv/weastronauts/web/app/themes/weastronauts-theme/bud.config.js",
        "/srv/weastronauts/web/app/themes/weastronauts-theme/composer.json",
        "/srv/weastronauts/web/app/themes/weastronauts-theme/tailwind.config.js",
        "/srv/weastronauts/web/app/themes/weastronauts-theme/theme.json",
        "/srv/weastronauts/web/app/themes/weastronauts-theme/tsconfig.json"
      ]
    }
  },
  "context": "/srv/weastronauts/web/app/themes/weastronauts-theme",
  "devtool": "inline-cheap-module-source-map",
  "infrastructureLogging": {
    "console": {
      "Console": {}
    },
    "level": "none"
  },
  "mode": "development",
  "module": {
    "noParse": {},
    "rules": [
      {
        "test": {},
        "exclude": [
          {}
        ],
        "parser": {
          "requireEnsure": false
        }
      },
      {
        "oneOf": [
          {
            "test": {},
            "include": [
              "/srv/weastronauts/web/app/themes/weastronauts-theme/resources"
            ],
            "use": [
              {
                "loader": "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/babel-loader/lib/index.js",
                "options": {
                  "cacheDirectory": "/srv/weastronauts/web/app/themes/weastronauts-theme/.budfiles/cache/babel",
                  "presets": [
                    [
                      "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/@babel/preset-env/lib/index.js"
                    ],
                    [
                      "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/@babel/preset-react/lib/index.js"
                    ]
                  ],
                  "plugins": [
                    [
                      "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/@babel/plugin-transform-runtime/lib/index.js",
                      {
                        "helpers": false
                      }
                    ],
                    [
                      "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js"
                    ],
                    [
                      "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/@babel/plugin-syntax-dynamic-import/lib/index.js"
                    ],
                    [
                      "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/@babel/plugin-proposal-class-properties/lib/index.js"
                    ]
                  ],
                  "env": {
                    "development": {
                      "compact": false
                    }
                  },
                  "root": "/srv/weastronauts/web/app/themes/weastronauts-theme"
                }
              },
              {
                "loader": "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/ts-loader/index.js",
                "options": {
                  "compiler": "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/typescript/lib/typescript.js",
                  "transpileOnly": true
                }
              }
            ]
          },
          {
            "test": {},
            "include": [
              "/srv/weastronauts/web/app/themes/weastronauts-theme/resources"
            ],
            "use": [
              {
                "loader": "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/style-loader/dist/cjs.js"
              },
              {
                "loader": "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/css-loader/dist/cjs.js",
                "options": {
                  "importLoaders": 1,
                  "sourceMap": true
                }
              },
              {
                "loader": "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/postcss-loader/dist/cjs.js",
                "options": {
                  "postcssOptions": {
                    "syntax": "postcss-scss",
                    "plugins": [
                      [
                        "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/postcss-import/index.js"
                      ],
                      [
                        null
                      ],
                      [
                        null
                      ],
                      [
                        "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/postcss-preset-env/dist/index.cjs",
                        {
                          "stage": 1,
                          "features": {
                            "focus-within-pseudo-class": false
                          }
                        }
                      ]
                    ]
                  },
                  "sourceMap": true
                }
              }
            ]
          },
          {
            "test": {},
            "include": [
              "/srv/weastronauts/web/app/themes/weastronauts-theme/resources"
            ],
            "use": [
              {
                "loader": "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/style-loader/dist/cjs.js"
              },
              {
                "loader": "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/css-loader/dist/cjs.js",
                "options": {
                  "importLoaders": 1,
                  "localIdentName": "[name]__[local]___[hash:base64:5]",
                  "modules": true,
                  "sourceMap": true
                }
              }
            ]
          },
          {
            "test": {},
            "include": [
              "/srv/weastronauts/web/app/themes/weastronauts-theme/resources"
            ],
            "type": "asset/resource",
            "generator": {
              "filename": "images/[name][ext]"
            }
          },
          {
            "test": {},
            "include": [
              "/srv/weastronauts/web/app/themes/weastronauts-theme/resources"
            ],
            "type": "asset/resource",
            "generator": {
              "filename": "images/[name][ext]"
            }
          },
          {
            "test": {},
            "include": [
              "/srv/weastronauts/web/app/themes/weastronauts-theme/resources"
            ],
            "type": "asset/resource",
            "generator": {
              "filename": "images/[name][ext]"
            }
          },
          {
            "test": {},
            "include": [
              "/srv/weastronauts/web/app/themes/weastronauts-theme/resources"
            ],
            "type": "asset",
            "generator": {
              "filename": "fonts/[name][ext]"
            }
          },
          {
            "test": {},
            "include": [
              "/srv/weastronauts/web/app/themes/weastronauts-theme"
            ],
            "exclude": [
              "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules"
            ],
            "type": "json",
            "parser": {}
          },
          {
            "test": {},
            "include": [
              "/srv/weastronauts/web/app/themes/weastronauts-theme"
            ],
            "exclude": [
              "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules"
            ],
            "use": [
              {
                "loader": "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/js-yaml-loader/index.js"
              }
            ]
          },
          {
            "test": {},
            "include": [
              "/srv/weastronauts/web/app/themes/weastronauts-theme"
            ],
            "exclude": [
              "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules"
            ],
            "use": [
              {
                "loader": "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/html-loader/dist/cjs.js"
              }
            ]
          },
          {
            "test": {},
            "include": [
              "/srv/weastronauts/web/app/themes/weastronauts-theme"
            ],
            "exclude": [
              "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules"
            ],
            "use": [
              {
                "loader": "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/csv-loader/index.js"
              }
            ]
          },
          {
            "test": {},
            "include": [
              "/srv/weastronauts/web/app/themes/weastronauts-theme"
            ],
            "exclude": [
              "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules"
            ],
            "use": [
              {
                "loader": "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/xml-loader/index.js"
              }
            ]
          },
          {
            "test": {},
            "include": [
              "/srv/weastronauts/web/app/themes/weastronauts-theme"
            ],
            "exclude": [
              "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules"
            ],
            "type": "json",
            "parser": {}
          },
          {
            "test": {},
            "include": [
              "/srv/weastronauts/web/app/themes/weastronauts-theme/resources"
            ],
            "use": [
              {
                "loader": "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/babel-loader/lib/index.js",
                "options": {
                  "cacheDirectory": "/srv/weastronauts/web/app/themes/weastronauts-theme/.budfiles/cache/babel",
                  "presets": [
                    [
                      "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/@babel/preset-env/lib/index.js"
                    ],
                    [
                      "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/@babel/preset-react/lib/index.js"
                    ]
                  ],
                  "plugins": [
                    [
                      "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/@babel/plugin-transform-runtime/lib/index.js",
                      {
                        "helpers": false
                      }
                    ],
                    [
                      "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js"
                    ],
                    [
                      "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/@babel/plugin-syntax-dynamic-import/lib/index.js"
                    ],
                    [
                      "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/@babel/plugin-proposal-class-properties/lib/index.js"
                    ]
                  ],
                  "env": {
                    "development": {
                      "compact": false
                    }
                  },
                  "root": "/srv/weastronauts/web/app/themes/weastronauts-theme"
                }
              },
              {
                "loader": "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/ts-loader/index.js",
                "options": {
                  "compiler": "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/typescript/lib/typescript.js",
                  "transpileOnly": true
                }
              }
            ]
          },
          {
            "test": {},
            "include": [
              "/srv/weastronauts/web/app/themes/weastronauts-theme/resources"
            ],
            "use": [
              {
                "loader": "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/style-loader/dist/cjs.js"
              },
              {
                "loader": "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/css-loader/dist/cjs.js",
                "options": {
                  "importLoaders": 1,
                  "sourceMap": true
                }
              },
              {
                "loader": "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/postcss-loader/dist/cjs.js",
                "options": {
                  "postcssOptions": {
                    "syntax": "postcss-scss",
                    "plugins": [
                      [
                        "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/postcss-import/index.js"
                      ],
                      [
                        null
                      ],
                      [
                        null
                      ],
                      [
                        "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/postcss-preset-env/dist/index.cjs",
                        {
                          "stage": 1,
                          "features": {
                            "focus-within-pseudo-class": false
                          }
                        }
                      ]
                    ]
                  },
                  "sourceMap": true
                }
              },
              {
                "loader": "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/resolve-url-loader/index.js",
                "options": {
                  "root": "/srv/weastronauts/web/app/themes/weastronauts-theme/resources",
                  "sourceMap": true
                }
              },
              {
                "loader": "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/sass-loader/dist/cjs.js",
                "options": {
                  "implementation": {
                    "sassNull": {},
                    "sassTrue": {
                      "value": true
                    },
                    "sassFalse": {
                      "value": false
                    },
                    "Logger": {
                      "silent": {}
                    },
                    "info": "dart-sass\t1.52.1\t(Sass Compiler)\t[Dart]\ndart2js\t2.17.1\t(Dart Compiler)\t[Dart]",
                    "types": {},
                    "NULL": {},
                    "TRUE": {
                      "value": true
                    },
                    "FALSE": {
                      "value": false
                    },
                    "default": {
                      "sassNull": {},
                      "sassTrue": {
                        "value": true
                      },
                      "sassFalse": {
                        "value": false
                      },
                      "Logger": {
                        "silent": {}
                      },
                      "info": "dart-sass\t1.52.1\t(Sass Compiler)\t[Dart]\ndart2js\t2.17.1\t(Dart Compiler)\t[Dart]",
                      "types": {},
                      "NULL": {},
                      "TRUE": {
                        "value": true
                      },
                      "FALSE": {
                        "value": false
                      }
                    }
                  },
                  "sourceMap": true
                }
              }
            ]
          }
        ]
      }
    ],
    "unsafeCache": false
  },
  "name": "bud",
  "node": false,
  "output": {
    "assetModuleFilename": "[name][ext]",
    "chunkFilename": "[name].js",
    "filename": "[name].js",
    "path": "/srv/weastronauts/web/app/themes/weastronauts-theme/public",
    "pathinfo": false,
    "publicPath": "/"
  },
  "optimization": {
    "emitOnErrors": false,
    "minimize": false,
    "minimizer": [
      "...",
      {
        "options": {
          "test": {},
          "parallel": true,
          "minimizer": {
            "options": {
              "preset": [
                "default",
                {
                  "discardComments": {
                    "removeAll": true
                  }
                }
              ]
            }
          }
        }
      }
    ],
    "runtimeChunk": "single",
    "splitChunks": {
      "cacheGroups": {
        "bud": {
          "chunks": "all",
          "test": {},
          "reuseExistingChunk": true,
          "priority": -10
        },
        "vendor": {
          "chunks": "all",
          "test": {},
          "reuseExistingChunk": true,
          "priority": -20
        }
      }
    }
  },
  "parallelism": 30,
  "performance": {
    "hints": false
  },
  "recordsPath": "/srv/weastronauts/web/app/themes/weastronauts-theme/.budfiles/bud/modules.json",
  "stats": {
    "preset": "errors-warnings"
  },
  "target": "browserslist:/srv/weastronauts/web/app/themes/weastronauts-theme/package.json",
  "plugins": [
    {
      "definitions": {
        "jQuery": "jquery",
        "$": "jquery"
      }
    },
    {
      "options": {}
    },
    {
      "patterns": [
        {
          "from": "/srv/weastronauts/web/app/themes/weastronauts-theme/resources/images",
          "to": "/srv/weastronauts/web/app/themes/weastronauts-theme/public/[name][ext]",
          "context": "/srv/weastronauts/web/app/themes/weastronauts-theme/resources",
          "noErrorOnMissing": true
        }
      ],
      "options": {}
    },
    {
      "options": {
        "assetHookStage": null,
        "basePath": "",
        "fileName": "manifest.json",
        "filter": null,
        "map": null,
        "publicPath": "",
        "removeKeyHash": {},
        "sort": null,
        "transformExtensions": {},
        "useEntryKeys": false,
        "useLegacyEmit": false,
        "writeToFileEmit": true
      }
    },
    {
      "key": "ESLintWebpackPlugin",
      "options": {
        "extensions": [
          "js",
          "jsx",
          "ts",
          "tsx",
          "vue"
        ],
        "emitError": true,
        "emitWarning": true,
        "failOnError": true,
        "cacheLocation": "/srv/weastronauts/web/app/themes/weastronauts-theme/.budfiles/cache/eslint",
        "cwd": "/srv/weastronauts/web/app/themes/weastronauts-theme",
        "eslintPath": "/srv/weastronauts/web/app/themes/weastronauts-theme/node_modules/eslint/lib/api.js",
        "resolvePluginsRelativeTo": "/srv/weastronauts/web/app/themes/weastronauts-theme",
        "threads": false
      }
    },
    {
      "options": {
        "emitHtml": false,
        "publicPath": ""
      },
      "plugin": {
        "name": "EntrypointsManifestPlugin",
        "stage": null
      },
      "name": "entrypoints.json"
    },
    {
      "name": "WordPressExternalsWebpackPlugin",
      "stage": null,
      "externals": {
        "type": "window"
      }
    },
    {
      "plugin": {
        "name": "WordPressDependenciesWebpackPlugin",
        "stage": null
      },
      "manifest": {},
      "usedDependencies": {},
      "fileName": "wordpress.json"
    },
    {
      "plugin": {
        "name": "MergedManifestPlugin"
      },
      "file": "entrypoints.json",
      "entrypointsName": "entrypoints.json",
      "wordpressName": "wordpress.json"
    }
  ],
  "resolve": {
    "alias": {
      "@src": "/srv/weastronauts/web/app/themes/weastronauts-theme/resources",
      "@dist": "/srv/weastronauts/web/app/themes/weastronauts-theme/public",
      "@fonts": "/srv/weastronauts/web/app/themes/weastronauts-theme/resources/fonts",
      "@images": "/srv/weastronauts/web/app/themes/weastronauts-theme/resources/images",
      "@scripts": "/srv/weastronauts/web/app/themes/weastronauts-theme/resources/scripts",
      "@styles": "/srv/weastronauts/web/app/themes/weastronauts-theme/resources/styles"
    },
    "extensions": [
      ".mjs",
      ".cjs",
      ".js",
      ".jsx",
      ".css",
      ".json",
      ".wasm",
      ".yml",
      ".toml",
      ".ts",
      ".tsx",
      ".scss",
      ".sass"
    ],
    "modules": [
      "/srv/weastronauts/web/app/themes/weastronauts-theme/resources",
      "node_modules"
    ]
  }
}

**Comment by retlehs** [comment]
howdy! github issues are for reporting bugs or making feature requests. please create a topic on https://discourse.roots.io/ for support.
