### ISSUE TITLE
Use `babel.config.js` instead of `.babelrc.js`

### ISSUE THREAD

**Issue by knowler** [roots/bud#15]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

As of Babel 7, `babel.config.js` is a project-wide config file and `.babelrc.js(on)` is a file-relative config file. I think a bud project should use the project-wide one, then developers can opt to use file-relative ones for individual blocks, etc.

https://babeljs.io/docs/en/config-files

**Comment by kellymears** [comment]
This change should be made against the next branch as it has diverged significantly from master and there will definitely be a conflict otherwise. 

Thanks for the PR @knowler 🤟🏽

**Comment by kellymears** [comment]
Addressed in 5769501edec58021ef2d20b84f2196bcf3147112.

Prettier kind of made a mess of that commit cleaning up the previous commit.. I guess Husky was taking a nap or something. Anyway, the relevant diff:

https://github.com/roots/bud/pull/13/commits/5769501edec58021ef2d20b84f2196bcf3147112#diff-8092285589d6d524c5a5696df1faacc1.

**Comment by kellymears** [comment]
I'm gonna keep this open until next is merged for 1.0.0.
