### ISSUE TITLE
Update @roots/bud-postcss docs for Bud 6

### ISSUE THREAD

**Issue by tedw** [roots/bud#1522]
I was just upgrading to Bud 6 and realized the [`@roots/bud-postcss`](https://bud.js.org/extensions/bud-postcss/) docs are still using the old `require.resolve()` syntax. I’ll defer to you all on what the new syntax should be but this worked for me:

```diff
bud.postcss.setPlugin('example-postcss-plugin', [
-  require.resolve('example-postcss-plugin'), // the plugin module path
+  'example-postcss-plugin',
  {stage: 1}, // options
])
```

Switching to `await bud.module.import('example-postcss-plugin')` also worked for me, as did specifying the options separately using `setPluginOptions()`:

```js
bud.postcss.setPluginOptions('example-postcss-plugin', {stage: 1});
```

**Comment by kellymears** [comment]
these docs updates are made. there are some relatively minor changes to the api in 6.3.0. Enough that we needed to bump the version. But, on the whole, the docs are improved alongside those changes.

Thanks for the issue
