### ISSUE TITLE
[bug] Use of static resources in CSS or HTML not working

### ISSUE THREAD

**Issue by danielkoch** [roots/bud#1533]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Describe the issue

Use of static images inside of stylesheet or HTML are not working correctly because the paths are converted wrong.

### Expected Behavior

The compiled path should converted to working relative paths like `../images/dummy.svg` or should include the theme path (`/wp-content/themes/<themename>/images/dummy.svg`).

### Actual Behavior

Use of static resources inside of CSS (example: `background-image: url('../images/test.svg');`) or using the arbitrary feature from Tailwind CSS (https://tailwindcss.com/docs/background-image#arbitrary-values) inside of HTML: `bg-[url()]` are not working.

The paths are converted to (`/images/dummy.svg`). This lead into a `404` request.

### Steps To Reproduce

1. Use static resource in CSS or HTML (see examples above)

### version

6.2.0

### What package manager are you using?

npm

### version

18.4.0

### Relevant .budfiles

module.exports = async (app) => {
	app
		.assets(['images'])
		.minimize()
		.hash()
		.template()
}

**Comment by kellymears** [comment]
This works. 

Sandbox of vanilla bud with images included in stylesheet:

[![Edit icy-water-v00rvx](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/icy-water-v00rvx?fontsize=14&hidenavigation=1&module=%2Fsrc%2Fglobal.css&theme=dark)

It looks like you need to set a publicPath since you are serving assets from a subdirectory. See: [docs/bud.setPublicPath](https://bud.js.org/docs/bud.setPublicPath)

```ts
module.exports = async (app) => {
app
  .assets(['images'])
  .minimize()
  .hash()
  .template()
  .setPublicPath('/wp-content/themes/[themename]/dist/')
}
```

Out of curiosity, why are you using `template` in the context of a WordPress theme?

**Comment by danielkoch** [comment]
Hello @kellymears,

thanks for pointing out this option.

I think I was misleaded by this documentation: https://docs.roots.io/sage/10.x/compiling-assets/#theme-assets – For HTML/PHP the `@asset` works as expected.  I thought I would get the same functionality also from bud.

With the mentioned option:
`.setPublicPath('/wp-content/themes/<my-theme-name>/public/')`
it works!

Regarding the `template()`. It must be rather `.template({enabled: false})` in my case. Think it was a left-over from the initial setup.

**Comment by kellymears** [comment]
Glad it's working out! 

One thing the Sage docs don't mention (I don't think) but is relevant: the assets subdirectories have import path aliases associated with them. You can use them to reference modules & assets without having to use relative paths:

```css
.selector {
  background-image: url(@images/dummy.svg)
}
```

```js
import dummy from '@images/dummy.svg'

document.querySelector('.selector').innerHTML = `
  <img src="${dummy}" />
`
```

There are aliases for `@scripts`, `@styles`, `@fonts` and `@images` (as well as `@resources`, if you have an asset module outside of one of the standard issue dirs). 

You can make additional aliases using [bud.alias](https://bud.js.org/docs/bud.alias).
