### ISSUE TITLE
[bug] dev overlay performance issues

### ISSUE THREAD

**Issue by iron-cherep** [roots/bud#1647]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Describe the issue

The overlay in development mode uses a css blur filter, which significantly affects performance

```css
backdrop-filter: blur(10px);
```

Since at the same time it gives only a visual effect, perhaps we can replace it with a static semitransparent background?

### Expected Behavior

The overlay's visual effects should not affect performance

### Actual Behavior

For clarity, I attach a line from Activity Monitor, which shows the load from one tab with an overlay opened. On my old Intel i7 MacBook Pro, this leads to constant lags and scrolling freezes

<img width="951" alt="Screenshot 2022-08-28 at 20 08 27" src="https://user-images.githubusercontent.com/18402060/187083757-ef193af9-d77f-418a-97da-c2176ccbbaa7.png">

### Steps To Reproduce

1. Run bud in dev mode
2. Cause the overlay to appear

### version

6.3.5

### What package manager are you using?

yarn classic

### version

1.22.19

### Configuration

```zsh
/**
 * @typedef {import("@roots/bud").Bud} bud
 *
 * @param {bud} app
 */
module.exports = async (app) => {
	app
		/**
		 * Sourcemaps in dev mode
		 */
		.when(app.isDevelopment, (bud) => bud.devtool())

		/**
		 * These files should be processed as part of the build
		 * even if they are not explicitly imported in application assets.
		 */
		.assets('images')

		/**
		 * Application entrypoints
		 *
		 * Paths are relative to your resources directory
		 */
		.entry({
			app: ['@scripts/app', '@styles/app'],
			editor: ['@scripts/editor', '@styles/editor'],
		})

		/**
		 * These files will trigger a full page reload
		 * when modified.
		 */
		.watch('resources/views/**/*', 'app/**/*')

		/**
		 * Target URL to be proxied by the dev server.
		 *
		 * This should be the URL you use to visit your local development server.
		 */
		.proxy(***)

		/**
		 * Development URL to be used in the browser.
		 */
		.serve('http://0.0.0.0:3000');
};
```

**Comment by kellymears** [comment]
I'm open to thinking about the use of `blur` but I'll have to do additional testing. This sounds kind of weird -- I'd think blur is a pretty common effect across the web these days; do you have problems on other sites?

@retlehs can you reproduce? 

on my m1 max and my base m1 mac mini everything is smooth.

**Comment by iron-cherep** [comment]
>This sounds kind of weird -- I'd think blur is a pretty common effect across the web these days; do you have problems on other sites?

I can't seem to remember a single popular site using this effect. Personally, I had an experience when using it for a single sticky header led to a performance regressions for users.

> on my m1 max and my base m1 mac mini everything is smooth.

It seems to be expected since m1 is kind of hi-end processor 😅

**Comment by retlehs** [comment]
On my Intel Mac I'm not seeing a difference in performance with or without the error overlay being visible.

> I can't seem to remember a single popular site using this effect.

FWIW, I feel like I come across sites using blur fairly often in the wild. I'm certain I've seen it on stripe.com somewhere — styles with blur exist in the stylesheets they serve at least 😅
