### ISSUE TITLE
[bug] webpack did not supply a source-map to SCSS files

### ISSUE THREAD

**Issue by aitormendez** [roots/bud#1682]
### Agreement

- [x] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Describe the issue

After install bud sass in Bedrock/Sage 10 I get this warning for each SCSS file when I run yarn build or yarn dev:

```
Error: resolve-url-loader: webpack misconfiguration
  webpack or the upstream loader did not supply a source-map
```

### Expected Behavior

No errors expected

### Actual Behavior

After install bud sass in Bedrock/Sage 10 I get this warning for each SCSS file when I run yarn build or yarn dev:

```
Error: resolve-url-loader: webpack misconfiguration
  webpack or the upstream loader did not supply a source-map
```

### Steps To Reproduce

1. Install Bedrock
2. Install Acorn
3. Install Sage
4. yarn add @roots/bud-sass --dev (Installed 6.4.0)
5. Rename other @roots package versions from `6.3.3` to `6.4.0` in package.json
6. Remove node_modules
7. yarn
8. Rename resources/styles from `*.css` to `*.scss`
9. yarn build (output error)

### version

6.4.0

### What package manager are you using?

yarn

### version

1.22.19

### Logs

```zsh
➜  sage git:(main) ✗ yarn build        
yarn run v1.22.19
$ bud build

◉  sage ./public [be3d0a7b60c5a7f0e6e2]
│
├─ ⚠ warning
│ Error: resolve-url-loader: webpack misconfiguration
│   webpack or the upstream loader did not supply a source-map
│
├─ ⚠ warning
│ Error: resolve-url-loader: webpack misconfiguration
│   webpack or the upstream loader did not supply a source-map
│
├─ entrypoints
│ ├─ app
│ │ ├─ js/runtime.8eb29a.js      1.02 kB
│ │ ├─ js/575.baac18.js        232 bytes
│ │ ├─ css/app.ed6516.css        6.29 kB
│ │ └─ js/app.735562.js        224 bytes
│ └─ editor
│   ├─ js/runtime.8eb29a.js      1.02 kB
│   ├─ js/575.baac18.js        232 bytes
│   ├─ css/editor.31d6cf.css
│   └─ js/editor.6413f2.js     376 bytes
│
├─ assets
│ └─ images/.gitkeep.31d6cf
│
│
└─ compiled 26 modules in 2s 17ms
```

### Configuration

```zsh
// @ts-check

/**
 * Build configuration
 *
 * @see {@link https://bud.js.org/guides/getting-started/configure}
 * @param {import('@roots/bud').Bud} app
 */
export default async (app) => {
  app
    /**
     * Application entrypoints
     */
    .entry({
      app: ["@scripts/app", "@styles/app"],
      editor: ["@scripts/editor", "@styles/editor"],
    })

    /**
     * Directory contents to be included in the compilation
     */
    .assets(["images"])

    /**
     * Matched files trigger a page reload when modified
     */
    .watch(["resources/views/**/*", "app/**/*"])

    /**
     * Proxy origin (`WP_HOME`)
     */
    .proxy("http://nomanisanisland.test")

    /**
     * Development origin
     */
    .serve("http://0.0.0.0:3000")

    /**
     * URI of the `public` directory
     */
    .setPublicPath("/app/themes/sage/public/");
};
```

**Comment by kellymears** [comment]
Can reproduce. Because it only emits a warning it didn't break e2e tests.

You can patch this in your config like so:

```ts
app.hooks.action(`build.before`, async app =>
  app.build.items.sass.setOptions({ sourceMap: true })
);
```

This is an easy fix. I'll try and release later today.

**Comment by tedw** [comment]
@kellymears Thanks for the quick response! I ran into the same issue this morning after upgrading to 6.4. I did try adding `sourceMap: true` but had the syntax messed up (had it nested within `sassOptions`). Works now 👍

**Comment by tedw** [comment]
@kellymears Just tested out 6.4.1, which resolved the sourcemap issue. However, if I set my own custom Sass options I still need to set `sourceMap: true` or else I get the resolve-url-loader error again. For example:

```js
app.build.items.sass.setOptions({
  additionalData: '@root {--foo: red;}',
  sourceMap: true,// removing this causes the error to return
});
```

I don’t think this is a huge deal but would be great if it could be fixed. If not, adding a note in the docs would be nice.

Thanks again for all your help and quick responses!

**Comment by kellymears** [comment]
@tedw Probably a better approach is to just lean on `bud.sass`, since it exposes an API specifically for your use case. It's reasonably well-documented: https://bud.js.org/extensions/bud-sass#global-values.

```ts
bud.sass.registerGlobal('@root {--foo: red;}')
```

Less well documented: you could also use the extensions api to set options with a callback: https://bud.js.org/guides/general-use/extensions#set-options

```ts
bud.sass.setOptions(
  options => ({ 
    ...options, 
    additionalData: '@root {--foo: red;}'
  })
)
```

Glad this issue is sorted for everyone. 🥂

**Comment by Arko0809** [comment]
Please can anyone tell me where to write this code ? 
app.build.items.sass.setOptions({
  additionalData: '@root {--foo: red;}',
  sourceMap: true,// removing this causes the error to return
});

**Comment by tedw** [comment]
@Arko0809 That code goes in your Bud config file https://bud.js.org/learn/config/files/bud.config

**Comment by Arko0809** [comment]
I have tried everything. 
Still the same error is occurring
