### ISSUE TITLE
[bug] Bud development server freezes when loading video

### ISSUE THREAD

**Issue by abel-sch** [roots/bud#1687]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Describe the issue

Bud freezes in dev mode whenever there's a video on the page

### Expected Behavior

Start bud dev by running `yarn dev` and have all pages hot module reloaded

### Actual Behavior

Whenever I visit a page where a video is present, the video is loading infinitely and Bud's dev server freezes

### Steps To Reproduce

1. Create a Sage theme
2. Add a page with a video
3. Run `yarn dev`

### version

6.4.1

### What package manager are you using?

yarn

### version

1.22.17

### Relevant .budfiles

```
export default async (app) => {
	app
		/**
		 * Application entrypoints
		 *
		 * Paths are relative to your resources directory
		 */
		.entry({
			app: ['@scripts/app', '@styles/app'],
			editor: ['@scripts/editor', '@styles/editor'],
			admin: ['@scripts/admin', '@styles/wp-admin'],
			login: ['@styles/login'],
			tinymce: ['@scripts/tinymce']
		})

		.provide({
			jquery: ['jQuery', '$']
		})

		.when(app.isProduction, bud => bud.setPublicPath('/app/themes/***/public/'))
		/**
		 * These files should be processed as part of the build
		 * even if they are not explicitly imported in application assets.
		 */
		.assets('images')

		/**
		 * These files will trigger a full page reload
		 * when modified.
		 */
		.watch('resources/views/**/*', 'app/**/*')

		/**
		 * Target URL to be proxied by the dev server.
		 *
		 * This should be the URL you use to visit your local development server.
		 */
		.proxy('https://***.test')

		/**
		 * Development URL to be used in the browser.
		 */
		.serve('http://0.0.0.0:3000');
};

```

**Comment by retlehs** [comment]
Howdy! The issue tracker on this repo is meant for reproducible bug reports and for feature requests. If you're able to provide the specific steps necessary to re-produce this on a vanilla Sage/Bud install, then we can re-open this issue.

FWIW, `<video>` elements are not causing this issue on either normal builds or dev builds on our end. Please post a topic on https://discourse.roots.io/ with additional details if you're looking for further help.
