### ISSUE TITLE
[bug] Bud error message overlay is always on top

### ISSUE THREAD

**Issue by kjvdven** [roots/bud#1694]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Describe the issue

When I run `yarn dev` and start my dev server and then I go to `http://0.0.0.0:3000`, I see my page as expected. 

But when I inspect something in the top of the page, I always inspect `<bud-error message=""></bud-error>`. It is always on top and blocking my inspector, even if there are no errors to be shown.

### Expected Behavior

When I inspect elements on the top of my page, such as my header and menu, I expect to select the header or the menu. 

### Actual Behavior

When I inspect elements on the top of my page, such as my header and menu, I end up inspecting the overlay inside `<bud-error message=""></bud-error>`.

### Steps To Reproduce

1. Run the dev server with `yarn dev`
1. Go to the theme page on `http://0.0.0.0:3000` 
1. Right click on something in the top part of the browser and click inspect
1. The developer tools open and the overlay in `<bud-error>` is selected.

### version

6.3.3

### What package manager are you using?

yarn

### version

1.22.19

### Configuration

```zsh
// @ts-check

/**
 * Build configuration
 *
 * @see {@link https://bud.js.org/guides/getting-started/configure}
 * @param {import('@roots/bud').Bud} app
 */
export default async (app) => {
  app
    /**
     * Application entrypoints
     */
    .entry({
      app: ["@scripts/app", "@styles/app"],
      editor: ["@scripts/editor", "@styles/editor"],
    })

    /**
     * Directory contents to be included in the compilation
     */
    .assets(["images", "svg"])

    /**
     * Matched files trigger a page reload when modified
     */
    .watch(["resources/views/**/*", "app/**/*"])

    /**
     * Proxy origin (`WP_HOME`)
     */
    .proxy("http:"//[removed]")

    /**
     * Development origin
     */
    .serve("http://0.0.0.0:3000")

    /**
     * URI of the `public` directory
     */
    .setPublicPath("/app/themes/sage/public/");
};
```

**Comment by kellymears** [comment]
this [was fixed in 6.3.4](https://github.com/roots/bud/releases/tag/v6.3.4)
