### ISSUE TITLE
[feature] sage theme.json: filter theme keys 

### ISSUE THREAD

**Issue by kellymears** [roots/bud#1714]
some of the tailwind theme values are very large objects (especially `colors`). 

we should allow these to be filtered so extraneous keys aren't generated for `theme.json`.

something like this:

```ts
app.wpjson.useTailwindColors([`black`, `white`, `transparent`, `indigo`, `custom-key.brand`])
```

**Comment by joshuafredrickson** [comment]
Hey @kellymears, here's the workaround you came up with for filtering `tailwind.colors`. Posting this here for future travelers looking to filter sooner than later. 🤙

```js
app.wpjson
  .useTailwindColors()
  .settings((settings) =>
    settings.mutate(`color.palette`, (palette) =>
      palette.filter((color) =>
        Object.keys(
          app.context.config[`tailwind.config.js`].module.theme.extend.colors
        ).includes(color.slug)
      )
    )
  );
```

**Comment by kellymears** [comment]
This is in 6.4.5, which is now released. The implementation is a bit simpler -- you just pass `true` to any of the tailwind theme.json generator fns to limit it to whatever is defined in `theme.extend`.

[Filter theme.json values to those used in theme.extend](https://bud.js.org/releases/6.4.5/#-rootssage-filter-themejson-values-to-those-used-in-themeextend).
