### ISSUE TITLE
Laravel Mix is compatible with Webpack Cli

### ISSUE THREAD

**Issue by dr5hn** [roots/bud#1716]
Hi bud team,

I think you need to update the comparison graph, as I see laravel mix is compatible with webpack cli.

![Screenshot 2022-09-27 at 11 51 18 AM](https://user-images.githubusercontent.com/6929121/192448230-4d78c390-1d1b-447d-bf04-670e924d4cfe.png)

https://laravel-mix.com/docs/6.0/cli#pass-options-to-webpack-cli
![Screenshot 2022-09-27 at 11 46 46 AM](https://user-images.githubusercontent.com/6929121/192448077-3d93c20d-2f65-47ec-bc31-27c104f229a5.png)

**Comment by kellymears** [comment]
laravel mix uses webpack-cli but that doesn't mean the user can. 

in comparison, you can use bud as a helper lib in a normal `webpack.config.js` file run with `webpack-cli` _directly_:

```ts
// webpack.config.js

import {factory} from '@roots/bud'

/**
 * For info on configuring webpack with a function or promise:
 * {@link https://webpack.js.org/configuration/configuration-types/#exporting-a-promise}
 */
export default async env => {
  /**
   * Instantiate bud
   */
  const bud = await factory({mode: env.mode})

  /**
   * Set entrypoints and do other config as usual
   */
  bud.entry('app', 'index.js').minimize().splitChunks()

  /**
   * This is our final config object. Return it for webpack.
   */
  return await bud.build.make()
}
```

it's not an insignificant difference. imagine you have a pre-existing application already set up for webpack-cli (maybe even some gulp scripts on the side). you aren't forced to retool _everything_ and you aren't required to use the bud cli at all. it should be a much more manageable transition.

approaching it from the opposite perspective: if you do have a `bud.config.js` file you can add a `webpack.config.js` file to your application root that exports the final config for direct use with `webpack-cli`:

```ts
import {get} from '@roots/bud'

export default async () => (await get()).build.make()
```

**Comment by dr5hn** [comment]
@kellymears Gotcha. Thanks for the explanation.

I believe we can also achieve the same by just installing webpack-cli (within the laravel mix project) and writing the same code within webpack.config.js
