### ISSUE TITLE
[bug] `useTailwindColors` includes all Tailwind colors in theme.json instead of only extended

### ISSUE THREAD

**Issue by joshuafredrickson** [roots/bud#1725]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Describe the issue

Bumping up from 6.3.5 to 6.4.4, and `useTailwindColors` includes the entire set of colors in Tailwind's default config. In 6.3.5, it only included the extended colors. 

I haven't tested it much further with regards to `useTailwindFontFamily` and `useTailwindFontSize`, but on first glance, it appears to be doing the same.

### Expected Behavior

`useTailwindColors` should include only colors from the `extend` key in the user's Tailwind config.

### Actual Behavior

Every Tailwind color is included, creating a `theme.json` file with 1200 lines. 🙃

### Steps To Reproduce

1. Clone `roots/sage` running bud 6.4.4
1. `yarn && yarn build`

### version

6.4.4

### What package manager are you using?

yarn classic

### Configuration

```zsh
// Default from roots/sage@latest

// @ts-check

/**
 * Build configuration
 *
 * @see {@link https://bud.js.org/guides/configure}
 * @param {import('@roots/bud').Bud} app
 */
export default async (app) => {
  app
    /**
     * Application entrypoints
     */
    .entry({
      app: ["@scripts/app", "@styles/app"],
      editor: ["@scripts/editor", "@styles/editor"],
    })

    /**
     * Directory contents to be included in the compilation
     */
    .assets(["images"])

    /**
     * Matched files trigger a page reload when modified
     */
    .watch(["resources/views/**/*", "app/**/*"])

    /**
     * Proxy origin (`WP_HOME`)
     */
    .proxy("http://example.test")

    /**
     * Development origin
     */
    .serve("http://0.0.0.0:3000")

    /**
     * URI of the `public` directory
     */
    .setPublicPath("/app/themes/sage/public/")

    /**
     * Generate WordPress `theme.json`
     *
     * @note This overwrites `theme.json` on every build.
     */
    .wpjson
      .settings({
        color: {
          custom: false,
          customGradient: false,
          defaultPalette: false,
          defaultGradients: false,
        },
        custom: {
          spacing: {},
          typography: {
            'font-size': {},
            'line-height': {},
          },
        },
        spacing: {
          padding: true,
          units: ['px', '%', 'em', 'rem', 'vw', 'vh'],
        },
        typography: {
          customFontSize: false,
        },
      })
      .useTailwindColors()
      .useTailwindFontFamily()
      .useTailwindFontSize()
      .enable()
};
```

**Comment by kellymears** [comment]
there is an issue to track adding this feature. https://github.com/roots/bud/issues/1714
