### ISSUE TITLE
[bug] Notifications no longer appearing after saving assets that trigger build

### ISSUE THREAD

**Issue by retlehs** [roots/bud#1750]
### Describe the issue

> Only one notification appears only once at the beginning, then no further notifications. 

h/t @daverobertson on the Roots Discord server

### Expected Behavior

Notifications on every build

### Steps To Reproduce

1. Open bud dev session
1. Save an asset that is being watched

### version

6.4.5

**Comment by kellymears** [comment]
I feel like this has been the case since 4.0.0. 

It used to work like this: 

https://github.com/roots/bud/blame/c8bc3ad124f9a301e3c5eaf5717b08b35da764a0/sources/@roots/bud/src/cli/commands/base.tsx#L210-L215

We can probably revert this change without a problem.

**Comment by kellymears** [comment]
FYI -- We are blocked on adding unit tests for bud cli because of a jest/clipanion issue.

**Comment by daverobertson** [comment]
Looks like this is occurring again with `yarn dev` on bud 6.6.6:

> Only one notification appears at the beginning, then no further notifications.
