### ISSUE TITLE
[bug] Dev session on network IP loads assets from 0.0.0.0

### ISSUE THREAD

**Issue by retlehs** [roots/bud#1765]
### Describe the issue

`bud dev` shows a nifty external IP address that can be used to visit the dev session from another device on your network. When visiting the external IP, bud serves assets from `0.0.0.0` instead of `192.168.x.x`, which results in missing styles

### Expected Behavior

The bud dev session shouldn't have any missing assets

### Actual Behavior

The bud dev session tries to load assets from `0.0.0.0`, which is unreachable unless you're on the same machine as the bud dev session

### Steps To Reproduce

1. `yarn dev`
1. Visit the provided external address		

### version

6.4.5

**Comment by retlehs** [comment]
A workaround that can be added to the Bud config for now:

```js
...

    app.proxy(`http://example.test`, searches => [
      ...searches,
      [`0.0.0.0:3000`, `192.168.xxx.xxx:3000`] // Replace with correct address
    ])
```

**Comment by kellymears** [comment]
want to make sure that our solution doesn't blow up existing docker configs that might be using a similar callback in `bud.proxy`.
