### ISSUE TITLE
[bug] `bud-stylelint`: Invisible terminal output text (VSCode)

### ISSUE THREAD

**Issue by strarsis** [roots/bud#1780]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Describe the issue

When using `roots/bud-stylelint` the output text in terminal is invisible (VSCode terminal).

### Expected Behavior

Normal, visible output text in terminal.

### Actual Behavior

Invisible output text in terminal.

### Steps To Reproduce

1. Install `@roots/bud-stylelint`
2. Run the build.
3. Note that all stylelint-related terminal output is invisible in VSCode terminal.

### version

6.5.0

### What package manager are you using?

npm

### version

8.19.2

### Configuration

```zsh
(Default configuration)
```

### Relevant .budfiles

(Default configuration)

**Comment by retlehs** [comment]
@strarsis I'm trying to reproduce this and I'm not able to

* Latest Sage, upgraded to Bud 6.5.0
* Added `@roots/bud-stylelint` as dep
* Added `.stylelintrc` from https://docs.roots.io/sage/10.x/compiling-assets/#linting
* Added to `app.css`:

```css
body {
  BACKGROUND: red;
}
```

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/115911/196048902-3c4233fc-082a-4ab6-bf06-6c04129ab99d.png">

**Comment by strarsis** [comment]
Maybe cause I disabled system effects or because of a GPU issue? I try to find out what is the cause of this. In WSL terminal the text is not invisible, only in VSCode terminal.
