### ISSUE TITLE
Add support for assets on both dev + default servers

### ISSUE THREAD

**Issue by mike-sheppard** [roots/bud#1785]
Hey folks 👋 this is a follow-up on the [discord chat](https://discord.com/channels/461985401494700032/970781592106713179/1031546452675145758) + [discourse forum thread](https://discourse.roots.io/t/uncaught-syntaxerror-expected-expression-got/24082/4) to track progress in one place. Appears this will take some time to resolve as it depends on Acorn v3+ release as potentially includes breaking changes.

**Issue**: when running the dev server, local assets (specifically dynamic imports) on the host domain do not load + errors are logged to the console

```javascript
Uncaught SyntaxError: expected expression, got '<'
```

**Running `yarn dev`**
- `localhost:3000` ✅ assets load perfectly
- `example.test` ❌ assets fail to load (ideally would like this to still serve assets even if they're not 'live reloaded')

**Running `yarn build`**
- `example.test` ✅ assets load perfectly

**Comment by kellymears** [comment]
With acorn v3, as of right now:

```ts
export default async bud => {
  bud
    .extensions.remove(`@roots/sage/acorn`)
    .setPublicPath(`/app/themes/roots/public/`)
    // ....
})
```

preliminary testing indicates that this works for `build` and `dev`.

**Comment by kellymears** [comment]
This should be fixed in [v6.6.0](https://bud.js.org/releases/6.6.0). There is no good way for bud.js to be sniff out the acorn version in use so you will need to opt-in:

```typescript
bud.sage.setAcornVersion('v3')
```

- https://bud.js.org/releases/6.6.0/#-fix-proxy-assets-load-when-in-dev-mode

**Comment by kellymears** [comment]
OK, as of 6.6.8 you no longer need to call `bud.sage.setAcornVersion` and development builds work in both the context of the dev server and the proxy server (publicPath is the same in both environments).

**Comment by mike-sheppard** [comment]
Started on a new site today and this is all working perfectly! 🎉 just wanted to say thanks
