### ISSUE TITLE
[bug] Bud `upgrade` command corrupts package.json bud related packages versions

### ISSUE THREAD

**Issue by jelovac** [roots/bud#1912]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Describe the issue

Running the command `npx bud upgrade` on `Sage` theme project root does not upgrade package versions correctly.

### Expected Behavior

The command should replace current bud related packages version with the specified version choosen when running the upgrade.

### Actual Behavior

Instead of specified version the following ends in package js:

```
  "devDependencies": {
    "@popperjs/core": "^2.11.6",
    "@roots/bud": "yarn info v1.22.19",
    "@roots/bud-eslint": "yarn info v1.22.19",
    "@roots/bud-prettier": "yarn info v1.22.19",
    "@roots/bud-sass": "yarn info v1.22.19",
    "@roots/bud-stylelint": "yarn info v1.22.19",
    "@roots/eslint-config": "yarn info v1.22.19",
    "@roots/sage": "yarn info v1.22.19",
    "browser-sync": "^2.27.10",
    "browser-sync-webpack-plugin": "^2.3.0"
  },
```

### Steps To Reproduce

1. Download Sage theme
2. Try to upgrade its bud dependencies by running `npx bud upgrade`

```
This command will replace all bud package related versions with "yarn info v1.22.19"
```

3. Then do yarn install

```
You will be asked to specify for each package the version you want from the list. Once specified the yarn will proceed to install packages. However the dependencies are never updated in the actual package.json.
```

### version

6.6.3

### What package manager are you using?

yarn

### version

1.22.19

**Comment by kellymears** [comment]
Thanks for the issue. 

Do you have a `yarn.lock` in your project? I can reproduce if I add an (empty) `yarn.lock` to one of our integration tests. Without `yarn.lock` it seems to function okay. 

We use `yarn.lock` to sniff for `yarn`:

```ts
  public async isYarn(): Promise<boolean> {
    try {
      return await realpath(join(this.path, `yarn.lock`)).then(
        result => typeof result === `string`,
      )
    } catch (e) {
      return false
    }
  }
```  

We should handle this but for now you can get this to work by deleting the yarn lockfile.

**Comment by jelovac** [comment]
> Thanks for the issue.
> 
> Do you have a `yarn.lock` in your project? I can reproduce if I add an (empty) `yarn.lock` to one of our integration tests. Without `yarn.lock` it seems to function okay.
> 
> We use `yarn.lock` to sniff for `yarn`:
> 
> ```ts
>   public async isYarn(): Promise<boolean> {
>     try {
>       return await realpath(join(this.path, `yarn.lock`)).then(
>         result => typeof result === `string`,
>       )
>     } catch (e) {
>       return false
>     }
>   }
> ```
> 
> We should handle this but for now you can get this to work by deleting the yarn lockfile.

Yes, I had yarn.lock file. Removing it and running the same command upgraded package.json to the latest available bud version.
