### ISSUE TITLE
[bug] dev server not working after update.

### ISSUE THREAD

**Issue by RomkaLTU** [roots/bud#1914]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Describe the issue

Dev server not working after update, nothing proxying:

![CleanShot 2022-12-03 at 12 30 17](https://user-images.githubusercontent.com/10167743/205436557-c22dbc95-a93c-4949-97f9-45222cb14eff.png)

### Expected Behavior

Can access site on http://0.0.0.0:3000 with is proxying to https://xxx.test

### Actual Behavior

Proxying not working. 

### Steps To Reproduce

1. Install sage10 and update JS dependencies to latest version
2. Run `yarn dev`

### version

6.6.4

### What package manager are you using?

yarn

### version

3.3.0

**Comment by danielkoch** [comment]
Same here. Dev server ist loading endless.

**Comment by kellymears** [comment]
Yep, fully aware. You should roll back to 6.6.2.

Will release fix as 6.6.5. PR: https://github.com/roots/bud/pull/1913

**Comment by danielkoch** [comment]
With the released version `6.6.5` it works for me. Thank you!

**Comment by kellymears** [comment]
and thank you for confirming, @danielkoch!
