### ISSUE TITLE
[feature] Decouple `theme.json` generator from Sage

### ISSUE THREAD

**Issue by nlemoine** [roots/bud#1932]
Hi!

I'm using bud in a theme that's not a Sage theme and would like to use the theme generator feature. Thing is it comes with all Sage  stuffs (aliases, paths, etc.) I don't need/want.

I quickly checked and not seing any dependency between the sage part and the theme.json part.

Would you think it could be possible?

**Comment by kellymears** [comment]
I was thinking about this recently as well. It makes sense to me.

**Comment by kellymears** [comment]
Okay, this work is done and included in [v6.6.10](https://github.com/roots/bud/releases/tag/v6.6.10). Still needs to be added to docs and then we can close this.

**Comment by nlemoine** [comment]
Thanks @kellymears! This is great news
