### ISSUE TITLE
Feature: InspectorControls example(s)

### ISSUE THREAD

**Issue by MWDelaney** [roots/bud#2]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

This might be a whole component can of worms, but an example of InspectorControls, with toggles, range, colors, etc. would be great to have.

**Comment by kellymears** [comment]
Color/opacity inspector controls open at #27.

**Comment by kellymears** [comment]
This issue has been moved to https://github.com/roots/bud-generators/issues/2
