### ISSUE TITLE
[bug] bud-vue not generate any bundle using .scss file 

### ISSUE THREAD

**Issue by riccardomel** [roots/bud#2126]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Describe the issue

Hi, i use the bud-vue extension, If i add this extension without added any futher bundle on bud.config file, the app.css generated after build **is empty with no errors on build console.**

If i simply remove from package.json the bud-vue extensions everything is good.

I tried with different node and bud version, same problem.

The problem seems in  the .scss files:

After installed bud-vue if i put a simply body{background:red} inside my app.scss the resulting app.css was empty. 

If i rename app.scss to app.css every works.

Please note: I already installed https://bud.js.org/extensions/bud-sass

If i remove bud-vue from deps every works file also with scss file.

Any advice?

### Expected Behavior

Using bud-vue with a app.scss file.

### Actual Behavior

The resulting bundle app.css is empty.

### Steps To Reproduce

1. install bud-vue
2. use app.scss file inside resources/styles/app.scss
3. npm run build
4. output of css/app.XXXX.css was empty
5. Now: remove bud-vue, and rebuild
6. app.XXXX.css is ok

### version

bud.js version (6.9.1)

### Relevant .budfiles

```zsh
/**
 * Build configuration
 *
 * @see {@link https://roots.io/docs/sage/ sage documentation}
 * @see {@link https://bud.js.org/guides/configure/ bud.js configuration guide}
 *
 * @typedef {import('@roots/bud').Bud} Bud
 * @param {Bud} app
 */

//import purgeCssWordPress from 'purgecss-with-wordpress';

export default async (app) => {
  /**
   * Application entrypoints
   * @see {@link https://bud.js.org/docs/bud.entry/}
   */
  app
    .entry({
      app: ['@scripts/app', '@styles/app'],
      vue: ['@scripts/vue'],
      editor: ['@scripts/editor', '@styles/editor'],
    }).minimize()


    /**
     * Directory contents to be included in the compilation
     * @see {@link https://bud.js.org/docs/bud.assets/}
     */
    .assets(['images'])

    /**
     * Matched files trigger a page reload when modified
     * @see {@link https://bud.js.org/docs/bud.watch/}
     */
    .watch(['resources/views', 'app'])

    /**
     * Proxy origin (`WP_HOME`)
     * @see {@link https://bud.js.org/docs/bud.proxy/}
     */
    .proxy('https://SITE')

    /**
     * Development origin
     * @see {@link https://bud.js.org/docs/bud.serve/}
     */
    .serve('http://0.0.0.0:3099')

    /**
     * URI of the `public` directory
     * @see {@link https://bud.js.org/docs/bud.setPublicPath/}
     */
    .setPublicPath('/app/themes/sage/public/')


    /*
    * Extensions
    * Purge
    * https://bud.js.org/extensions/bud-purgecss/
    * */
    /*.purgecss({
      content: [app.path(`resources/views/**`)],
      safelist: [...purgeCssWordPress.safelist],
    })*/


    /*
    * Critical
    * https://bud.js.org/extensions/bud-criticalcss
    * */


    /**
     * Generate WordPress `theme.json`
     *
     * @note This overwrites `theme.json` on every build.
     *
     * @see {@link https://bud.js.org/extensions/sage/theme.json/}
     * @see {@link https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/}
     */
    .wpjson.settings({
      color: {
        custom: false,
        customDuotone: false,
        customGradient: false,
        defaultDuotone: false,
        defaultGradients: false,
        defaultPalette: false,
        duotone: [],
      },
      custom: {
        spacing: {},
        typography: {
          'font-size': {},
          'line-height': {},
        },
      },
      spacing: {
        padding: true,
        units: ['px', '%', 'em', 'rem', 'vw', 'vh'],
      },
      typography: {
        customFontSize: false,
      },
    })
    .useTailwindColors()
    .useTailwindFontFamily()
    .useTailwindFontSize()
    .enable();

};
```

**Comment by kellymears** [comment]
Not sure, at first glance it seems to be behaving fine (both standard stylesheets and vue SFC template tags (`<style lang="scss">`).

Here is a sandbox:

https://codesandbox.io/p/sandbox/bud-vue-sass-cx4fnh?file=%2Fsrc%2Findex.scss&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A8%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A8%7D%5D

**Comment by riccardomel** [comment]
Hi the issue is with SAGE  presets
