### ISSUE TITLE
[bug/request/question] Imports without file extension fail - Upgrade from 6.4.5 -> 6.11.0

### ISSUE THREAD

**Issue by flmuel** [roots/bud#2160]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### The feature

Hello all,
unfortunately had to notice that after updating to the latest Bud version, the following error occurs during compilation:
```
Did you mean 'index.js'?
BREAKING CHANGE: The request './folder' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": 
"module"').
```
My whole project consists of imports which reference relative JS files or index.js files in folders.
I haven't found a single hint about this and wanted to ask if you have a tip for me, how I can work around the error? The Webpack attribute "fullySpecified" did not help me with the solution, or I did something wrong when filtering/overwriting the config.
Or is it ready planned to add the feature again?
I also saw that in a release the config was switched back to the .js extension. So I renamed my bud.config.mjs again as well. Does the file type still have any influence? To me it seemed like it didn't matter.

**Comment by kellymears** [comment]
This was an upstream change. 

If you remove `{type: 'module'}` from `package.json` and change the bud config to `bud.config.mjs` you won't see this error.

alternatively, filter the rules provided to the compiler: 

```js
app.hooks.on(`build.module.rules.oneOf`, (rules) =>
    rules.map((rule) =>
      !rule.test.test(`.js`)
        ? rule
        : { ...rule, resolve: { fullySpecified: false } },
    ),
)
```

But, I would use this codemod and fix the project to be in spec with esm imports: https://github.com/codemodsquad/jscodeshift-add-imports.

**Comment by flmuel** [comment]
Thank you Kelly!
I will go with the filter... there is a little typo in your snippet, here with fixed code:
```js
app.hooks.on(`build.module.rules.oneOf`, (rules) =>
    rules.map((rule) =>
      !rule.test.test(`.js`)
        ? rule
        : { ...rule, resolve: { fullySpecified: false } },
    ),
  )
  ```

**Comment by kellymears** [comment]
Cool, updated my sample in case someone anxiously copy/pastes it. Closing this!
