### ISSUE TITLE
[request] `wpjson.settings` callback `fn` required to return passed `theme` instance; missing generated `theme.json` parts otherwise

### ISSUE THREAD

**Issue by strarsis** [roots/bud#2168]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Describe the issue

The `wpjson.settings` callback function has to return the `theme` instance which it got passed as argument, 
as otherwise parts of generated `theme.json` will be missing, and not just the parts added after the callback function.

### Expected Behavior

No missing parts of generated `theme.json`, even if the callback function does not return the `theme` instance.

### Actual Behavior

Parts of `theme.json` is missing when the callback function does not return the `theme` instance:

### Steps To Reproduce

1. Start with a default Sage theme with default `bud` configuration.
2. Run the `bud` build. (Optional: Keep/copy generated `theme.json` for later comparison with a newly generated `theme.json`).
3. Add to `bud` config a `wpjson.settings` invocation with a callback function that does not return the `theme` instance that was passed to it as argument:
```js
// [...]
      .settings(theme => {
        // logic that does not return `theme`
       // return theme; // do not return `theme` instance to reproduce this issue
      })
// [...]
````
4. Run the `bud` build, note that parts of newly generated `theme.json` are missing now.

### version

6.9.1

### Logs

```zsh
No notices, warnings or errors were logged.
```

### Configuration

```zsh
Default `bud` config file, except for the added `wpjson.settings` for reproducing this issue.
```

**Comment by kellymears** [comment]
I'm willing to hear out arguments for the behavior being different, but this function is working as intended (and [as documented](https://bud.js.org/extensions/sage/theme.json#managing-the-settings-field)).

It gives you the object and asks you to return something:

```ts
export interface Mutator {
  (
    json:
      | Partial<Theme.GlobalSettingsAndStyles['settings']>
      | Container<Partial<Theme.GlobalSettingsAndStyles['settings']>>,
  ):
    | Partial<Theme.GlobalSettingsAndStyles['settings']>
    | Container<Partial<Theme.GlobalSettingsAndStyles['settings']>>
}

interface settings {
  (
    input?:
      | Mutator
      | Container<Partial<Theme.GlobalSettingsAndStyles['settings']>>
      | Partial<Theme.GlobalSettingsAndStyles['settings']>
      | boolean,
    raw?: boolean,
  ): this
}
```

I think it's more confusing for this function to not use what is returned as a value. And it's pretty easy to always return a value with arrow fns and the container interface:

```js
bud.wpjson.settings(theme => theme
  .set('color.custom', false)
  .set('color.customDuotone', false)
)
```

Regardless, `wpjson.settings` should arguably be deprecated in #2079 (currently not planning on  that). But, I would use `bud.wpjson.set` over `bud.wpjson.settings` (PR soon on sage itself):

```js
bud.wpjson
  .set(`settings.color.custom`, false)
  .set(`settings.color.customDuotone`, false)
  .set(`settings.color.customGradient`, false)
  .set(`settings.color.defaultDuotone`, false)
```
