### ISSUE TITLE
[request] Regenerate theme.json when tailwind.config.js updated

### ISSUE THREAD

**Issue by weilinzung** [roots/bud#2275]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### The feature

Hi,

In Sage 10, we have to stop `yarn dev` every time after updating the `tailwind.config.js` or any new tailwind configs wouldn't be applied.

Thanks!

### Use case

It would be a faster development if we could be able to watch `tailwind.config.js` and regenerate `theme.json`, then auto-reload the page.

**Comment by kellymears** [comment]
I have to think about how to do this in a way that doesn't cause a lot of overhead. Parsing tailwind and rewriting the json is relatively resource/time intensive. 

For now you might want to consider using something like nodedemon to restart the process when the fs state changes https://github.com/remy/nodemon. 

Thinking this through: active browser window will pick up and apply state changes once the server comes back after restarting. But, we might need to add something in the client to instigate the auto refresh.

**Comment by weilinzung** [comment]
@kellymears We could be able to use `bud` to watch `tailwind.config.js` file, but yeah, it wouldn't recompile.
 
thanks for the idea, but still looking for a naive way to support this request.

**Comment by kellymears** [comment]
@weilinzung in [6.14.1](https://github.com/roots/bud/releases/tag/v6.14.1) `theme.json` should be updated whenever its dependencies (including `tailwind.config.*`) change. 

So you can get auto reload in the browser by adding `tailwind.config.js` to your watched paths:

```ts
bud.watch(['resources/views', 'app', 'tailwind.config.js']);
```

Don't add `theme.json` as that will cause the window to reload on every change. 

There is some jank if your tailwind config can't be parsed (syntax error, etc.), which will be thrown by `tailwindcss`, `sucrase` or `jiti`, depending on how you've authored your tailwind config. 

In that case you will likely still need to restart the process to get it back on track. I'm not sure yet how this type of error is different from a normative client code error but @roots/bud-client is much less likely to deal with it gracefully. Probably can be improved in a future release.
