### ISSUE TITLE
[bug] create-bud-app always builds TS project even if option is un-checked 

### ISSUE THREAD

**Issue by bnjmnrsh** [roots/bud#2550]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Describe the issue

Same creation and configuration process as #2549

Forgive me if this is just me not understanding the project intent, but when using `create-bud-app`, I've scaffolded a project _without_ typescript. Still, the resulting project appears to be configured for TS, the bud.js config lists `index.ts` as an entry point, and the js resources in `/src/` are `. ts`.

### Expected Behavior

If the typescript option is unchecked, I was expecting the project not to have TS ass a dev-dep and instead set up for vanilla.js. 

### Actual Behavior

The project is scaffolded with typescript.

```
  "devDependencies": {
    "@roots/bud": "^6.20.0",
    "@roots/bud-babel": "^6.20.0",
    "@roots/bud-eslint": "^6.20.0",
    "@roots/bud-postcss": "^6.20.0",
    "@roots/bud-preset-wordpress": "^6.20.0",
    "@roots/bud-prettier": "^6.20.0",
    "@roots/bud-sass": "^6.20.0",
    "@roots/bud-stylelint": "^6.20.0",
    "@roots/bud-swc": "^6.20.0",
    "@roots/eslint-config": "^6.20.0",
    "typescript": "^5.3.3"
  }
```

### Steps To Reproduce

1. npx create-bud-app --wordpress --customize
2. npm
3. wordpress
4. swc
5. sass
6. (no libraries/frameworks)
7. eslint, prettier,stylelint
8. 1.HTML wrapper - no

### version

(preview release)

### Logs

```zsh
NA
```

### Configuration

```zsh
NA
```

### Relevant .budfiles

```zsh
NA
```

**Comment by bnjmnrsh** [comment]
It seems to install `postcss` even though it was also unchecked.

**Comment by kellymears** [comment]
## `typescript` included

This is intended and has to do with your choice to install eslint and swc in combination. 

swc supports typescript natively. The default is to set the project up for typescript but with no typechecking enforcement. 

In order for eslint to parse typescript files it is required to use `@typescript-eslint/eslint-plugin`, which in turn requires `typescript` available as a peer dependency.

You could remove `'@roots/eslint-config/typescript'` from `.eslintrc.cjs` and `typescript` from devDependencies and be fine.

## `postcss` included 

`@roots/bud-postcss` used to be a dependency of `@roots/bud-sass`. It is now possible to install `@roots/bud-sass` without `@roots/bud-postcss`. But, `@roots/bud-preset-wordpress` and `@roots/bud-preset-recommend` both include it as a dependency, as it is the recommendation. So, you can remove it from devDependencies but it will still be included by `@roots/bud-preset-wordpress` anyway. 

Maybe this can be improved in a future release, but postcss is already a dependency of a lot of other utilities involved in the build (like the css extract tooling), so the savings is likely only going to be like ~10mb from `node_modules` (just guessing).

I can and will remove `@roots/bud-postcss` as a dependency of `@roots/bud-sass` in the `create-bud-app` business logic, however. Which will at least stop it from being listed in `package.json`, even though it will still be used.

**Comment by bnjmnrsh** [comment]
Hi Kelly - Thanks for the details, super valuable.

Many thanks,
Ben
