### ISSUE TITLE
Tailwind logical properties classes does not work as expected

### ISSUE THREAD

**Issue by alaa-alshamy** [roots/bud#2597]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Describe the issue

Tailwind logical properties classes does not work as expected

### Expected Behavior

When I use for example `ms-1` css class, tailwind should use `margin-inline-start`, like following:

```
.ms-1 {
    margin-inline-start: 0.25rem;
}
```

### Actual Behavior

It actullay use `margin-left`, like following:

```
.ms-1 {
    margin-left: 0.25rem;
}
```

### Steps To Reproduce

Just create a new sage theme and use one of the logical properties classes for example `ms-1`, none of them working as expected

### version

6.20.0

**Comment by retlehs** [comment]
I think this is a Browserslist config issue. On one of my projects, I opened package.json and made this change:

```diff
  "browserslist": [
-    "extends @roots/browserslist-config"
+    "extends @roots/browserslist-config/wordpress"
  ],
```

After re-running the build using this modified Browerslist config, I'm seeing `.ms-1` with the expected CSS (`margin-inline-start: .25rem;`)

Ref https://github.com/roots/bud/blob/main/sources/%40roots/browserslist-config/docs/configs.mdx

**Comment by retlehs** [comment]
I'm closing this out since the behavior is actually expected with our default Browerslist configuration at this time

You can modify your own Browerslist configuration to reflect your needs

**Comment by alaa-alshamy** [comment]
Yes you are right, Big Thanks @retlehs
