### ISSUE TITLE
[bug] Purgecss doesn't recalculate styles after file change in watch mode

### ISSUE THREAD

**Issue by spichkaJohn** [roots/bud#2622]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Describe the issue

I use purgecss in my bud config and it does its job.

But I need to restart dev server each disable purgecss and enable after some changes to verify that there was no unnecessary removals. In the `bud dev` watch mode, markup is automatically updating, but some bootstrap classes purged If I didn't use them before. 

Part of my `bud.config.js`

```
app.purgecss({
      content: [
        app.path(`resources/views/**`)
      ],
      safelist: {
        ...purgeCssWordPress.safelist,
        ],
      },
    });

  /**
   * Development server settings
   *
   * @see {@link https://bud.js.org/docs/bud.setUrl}
   * @see {@link https://bud.js.org/docs/bud.setProxyUrl}
   * @see {@link https://bud.js.org/docs/bud.watch}
   */
  app
    .setUrl('http://localhost:8001')
    .setProxyUrl('http://localhost:8000')
    .watch(['resources/views', 'app']);
};

```

### Expected Behavior

Purgecss recalculates styles each time I update files under `watch`. 

Bootstrap util classes with the corresponding styles added to the css automatically even if they were purged before because I didn't use this class in the markup.

### Actual Behavior

After `bud dev` unnecessary css is purged, but after I use new bootstrap class that was not in the files before on existing markup I need to restart dev server to have styles from this class.

### Steps To Reproduce

1. Start dev server
1. Add new bootstrap class to the markup or change existing to that is not used before in the codebase
1. See that you need to restart dev server to apply styles, because even live reload updated the markup there are no new styles from the added class.

### version

6.23.1

**Comment by kellymears** [comment]
I wouldn't purge in development mode. 

Something like this:

```ts
bud.when(bud.isProduction, bud => bud.purgecss({
  content: [
    app.path(`resources/views/**`)
  ],
  safelist: [
    ...purgeCssWordPress.safelist,
  ],
})
```

Or, use the newer way of handling this, since it will not enable the plugin in development mode:

```ts
bud.purge
  .setContent([bud.path(`resources/views/**`)])
  .setSafelist([...purgeCssWordPress.safelist])
```

I realize now that I need [to update the documentation](https://bud.js.org/extensions/bud-purgecss). Leaving this issue open as a reminder.

**Comment by kellymears** [comment]
Updated documentation: https://bud.js.org/extensions/bud-purgecss. 

Thanks for filing this issue and using bud.js!
