### ISSUE TITLE
[request] Hooks for MiniCssExtractPlugin and CopyPlugin filenames

### ISSUE THREAD

**Issue by oxyc** [roots/bud#2633]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### The feature

There are hooks for `build.output.filename` and `build.output.assetModuleFilename` but nothing similar for the filenames used in `MiniCssExtractPlugin` and `CopyPlugin`.

Feature would be to expose hooks for these.

### Use case

I want to use query based hashes so that I can use WP own `block.json` asset loader.

### Notes

I got it working with `build.plugins` but it's a bit messy and would be nice to have hooks.

https://github.com/generoi/bedrock/blob/feature/bud/web/app/themes/gds/build/bud-block.js#L45-L63

**Comment by kellymears** [comment]
It's been a struggle for me to effectively document the extensions api, so I don't blame you for not knowing it's available. Both of your use cases are covered by it.

You can get ahold of any extension by using `bud.extension.get` and passing it the import path of the module. In your case you're trying to get `@roots/bud-extensions/mini-css-extract-plugin` and `@roots/bud-extensions/copy-webpack-plugin`. You can get a list of all the extensions by running `bud doctor`.

So, to modify the filename used by mini css, you would do this:

```ts
bud.extensions
  .get('@roots/bud-extensions/mini-css-extract-plugin')
  .setFilename('[name].css')
```

For the copy plugin you can just add the pattern object directly, as per the webpack copy plugin docs:

```ts
bud.extensions.get('@roots/bud-extensions/copy-webpack-plugin')
  .setPatterns([
    {
      from: bud.path('package.json'),
      to: '[name].json',
    },
  ])
```

Neither of these extensions do any sort of filtering on the options once they are set, so you will have the last word.

Even though the documentation is poor the typings are pretty solid, so you'll get feedback if it's set up correctly in your editor:

<img width="655" alt="Screenshot 2024-08-10 at 03 55 32" src="https://github.com/user-attachments/assets/52eca99a-cb7f-4e0d-ae58-c71a4827b0b7">

As an aside, for the copy plugin options, [bud.assets lets you specify a pattern object directly](https://bud.js.org/reference/bud.assets#copying-using-an-object).

**Comment by oxyc** [comment]
ah thanks! that seems way better thanks hooks, i’ll go ahead and close this feature request

**Comment by jasperf** [comment]
@kellymears I was trying @oxyc 's suggested
```
app.build.items.precss.setLoader('minicss');
  app.hooks.action('build.before', (bud) => {
    bud.extensions.get('@roots/bud-extensions/mini-css-extract-plugin').enable(true);
  });
```

as discussed at https://discourse.roots.io/t/editor-css-application-in-sage-10/28030/7 and that works showing styles for desktop, tablet and mobile but then I get a notice error

```
Uncaught TypeError: Cannot read properties of null (reading 'createInfoNotice')
    at handler (editor.js:35:86)
    at Module.load (editor.js:42:20)
    at Module.register (filters.js:9:99)
    at eval (editor.js:13:59)
    at ./scripts/editor.js (editor.js:732:1)
    at options.factory (9731c5f8-594e-4c67-a921-87fcac39ec78:731:31)
    at __webpack_require__ (9731c5f8-594e-4c67-a921-87fcac39ec78:139:33)
    at __webpack_exec__ (editor.js:746:61)
    at editor.js:747:139
    at webpackJsonpCallback (9731c5f8-594e-4c67-a921-87fcac39ec78:1403:39)
blob:https://site/ccd23bf7-2100-4333-b3f9-4a704bf1e0a8
```


Also tried
```
**
* MiniCssExtractPlugin setup using Bud's extension system
*/
 app.extensions.get('@roots/bud-extensions/mini-css-extract-plugin').setFilename('[name].css');
```

before, but no css seemed to be working / compiled  running `yarn dev` after. So either I am doing something wrong or I am skipping  some step post changes. just wanted editor to show my editor styles, especially on tablet and mobile.

Am looking into @kellymears 's mentioned
```
bud.extensions
  .get('@roots/bud-extensions/mini-css-extract-plugin')
  .setFilename('[name].css')
```

but that seems the same as my earlier code but applied to the Sage 10 app.
as well some now.
