### ISSUE TITLE
[request] Interactivity API

### ISSUE THREAD

**Issue by r-chrzan** [roots/bud#2649]
### The feature

Is there any support for Interactivity API?

**Comment by retlehs** [comment]
What isn’t working for you? What have you tried?

Please move this discussion to Roots Discourse unless you’ve got some specific requests for the project

**Comment by kellymears** [comment]
I haven't tried the Interactivity API and don't have any plans to in the future, but according to the release post I think all of our WordPress specific Webpack plugins and bud.js extensions are compatible.

> It’s important to highlight that the block creation workflow doesn’t change.
https://make.wordpress.org/core/2024/03/04/interactivity-api-dev-note/
