### ISSUE TITLE
[bug] `@roots/sage`: aliases not set / set incorrectly

### ISSUE THREAD

**Issue by strarsis** [roots/bud#2660]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Describe the issue

`@roots/sage` (current (`v6.23.3`) version) should [set additional aliases](https://bud.js.org/reference/bud.alias#rootssage).
However, those aliases have incorrect paths, except for `@styles`.

As a workaround, e.g. for the `@fonts` alias, it has to be explicitly set with `@src` alias:
`app.path('@fonts')` => `/home/user/src/project-folder/site/web/app/themes/sage10/src/fonts`
`app.setPath('@fonts', app.path('@src/fonts'));`
`app.path('@fonts')` => `/home/user/src/project-folder/site/web/app/themes/sage10/resources/fonts`

### Expected Behavior

Correct paths for the listed, additional aliases by `@roots/sage` (`@scripts`; `@fonts`; `@images`), except for `@styles`:
- `@scripts: /home/user/src/project-folder/site/web/app/themes/sage10/resources/scripts`
- `@styles:  /home/user/src/project-folder/site/web/app/themes/sage10/resources/styles`
- `@fonts:   /home/user/src/project-folder/site/web/app/themes/sage10/resources/fonts`
- `@images:  /home/user/src/project-folder/site/web/app/themes/sage10/resources/images`

### Actual Behavior

Incorrect paths for the listed, additional aliases by `@roots/sage` (`@scripts`; `@fonts`; `@images`), except for `@styles`:
- `@scripts: /home/user/src/project-folder/site/web/app/themes/sage10/src/scripts`
- `@styles:  /home/user/src/project-folder/site/web/app/themes/sage10/resources/styles`
- `@fonts:   /home/user/src/project-folder/site/web/app/themes/sage10/src/fonts`
- `@images:  /home/user/src/project-folder/site/web/app/themes/sage10/src/images`

### Steps To Reproduce

1. Use one of the additional aliases by `@roots/sage` (`@scripts`; `@fonts`; `@images`), except for `@styles`.
2. Note that the paths using those aliases are incorrect, hence folders/files cannot be found (e.g. by `assets(...)`.

### version

6.23.3

**Comment by kellymears** [comment]
OK, this fix will be rolled out in 6.24.1 which I'm aiming to release later this week.

**Comment by kellymears** [comment]
Thanks @strarsis for the issue and patience ✌🏼
