### ISSUE TITLE
Feature: Optional front-end javascript

### ISSUE THREAD

**Issue by MWDelaney** [roots/bud#5]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

Blocks should be able to compile and enqueue a front-end javascript bundle.

**Comment by kellymears** [comment]
This is largely setup right now.

The generated `registerBlockType` function in `block.php` just needs to have the script and style added to registration.

```php
    /**
     * Register block.
     *
     * @param  string
     * @return void
     */
    protected function registerBlockType(string $block): void
    {
      register_block_type($block, [
        'editor_script' => "{$block}/editor/js",
        'editor_style' => "{$block}/editor/css",
      ]);
    }
```

becomes:

```php
    /**
     * Register block.
     *
     * @param  string
     * @return void
     */
    protected function registerBlockType(string $block): void
    {
      register_block_type($block, [
        'editor_script' => "{$block}/editor/js",
        'editor_style' => "{$block}/editor/css",
        'script' => "{$block}/public/js",
        'style' => "{$block}/public/css",
      ]);
    }
```

We can make this easier to configure near the top of the class, but the bones of it are all in place. Currently, it's just set up for the broadest, most minimal use case.
