### ISSUE TITLE
Bud accidentally itself when using `bud init`. Is this dangerous?

### ISSUE THREAD

**Issue by QWp6t** [roots/bud#567]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

When using `yarn bud init`, for example, bud appears to delete itself from node_modules.

## Steps to reproduce

0. set up a repo with a bud config that uses an extension that has dependencies
1. `yarn install`
2. `yarn bud init` <-- oopsie! 💀
3. `yarn bud build` <-- fails 😢

**Expected behavior:** I want my `node_modules/@roots` folder to still exist

**Actual behavior:** My `node_modules/@roots` gets deleted

**Reproduces how often:** 💯

## Versions

v5.0.0-next.0 on Ubuntu via WSL2 in Windows 10

## Additional information

I didn't check, but it might actually be wiping out the entire node_modules folder before installing dependencies, but it probably shouldn't be doing that either.

**Comment by kellymears** [comment]
that reminds me of the time i accidentally 26kb of #699, good times

**Comment by kellymears** [comment]
I think this is no longer relevant since we manage resolution of internal dependencies now.
