### ISSUE TITLE
Return value of Roots\Bud\Manifest\Base\AbstractManifest::asset() must be an instance of Roots\Bud\Asset\Asset, null returned

### ISSUE THREAD

**Issue by cspicuzza** [roots/bud#64]
## Description

After activating my first plugin generated from Bud, this error appeared in WP: 

`Return value of Roots\Bud\Manifest\Base\AbstractManifest::asset() must be an instance of Roots\Bud\Asset\Asset, null returned`

## Steps to reproduce

1. npx @roots/bud@1.0.0-rc.4 init (tried rc.6 as well)
2. yarn bud generate
3. went through the flow then activated my plugin

**Expected behavior:** Plugin to activate

**Actual behavior:** TypeError

**Reproduces how often:** 100%

## Versions

I tried using 1.0.0-rc.4 and 1.0.0-rc.6

**Comment by kellymears** [comment]
Thanks for the issue. I'll look into this. 👍🏼

**Comment by kellymears** [comment]
The two merges above fix this issue for me.

You should be able to run `composer update` and `bud generate wp-plugin .` in your project to pick up those changes.

**Comment by cspicuzza** [comment]
@kellymears looks ok now.  thanks for the quick fix!
