### ISSUE TITLE
Scripts get wrong dependency when using @wordpress/icons package

### ISSUE THREAD

**Issue by alexdanylyschyn** [roots/bud#719]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

When trying to use one of the Gutenberg Icons from the @wordpress/icons package the script won't get enqueued by acorn because bud is adding "wp-icons" as a dependency to the entrypoints.json file. wp-icons doesn't exist and can't be enqueued by wordpress.

## Steps to reproduce

1. create a JS file like this:

```
import { registerBlockType } from '@wordpress/blocks';
import { globe as icon } from '@wordpress/icons';

import Edit from './edit';
import save from './save';

registerBlockType('example/block', {
  icon,
  /**
   * @see ./edit.js
   */
  edit: Edit,

  /**
   * @see ./save.js
   */
  save,
});
```

2. run `bud build`
3. check entrypoints.json if there is a "wp-icons" dependency

**Expected behavior:** The script should get enqueued and @wordpress/icons shouldn't get extracted / referenced as an external

**Actual behavior:** @wordpress/icons gets treated like the other externals and the script won't enqueue

**Reproduces how often:** everytime.

## Versions

@roots/bud/5.0.0-next.16 linux-x64 node-v16.13.0

**Comment by kellymears** [comment]
Thank you for the bug report and the extra context. The PR mentioned above should fix this issue.
