### ISSUE TITLE
Feature Request: Hi, how do I use bud in windows

### ISSUE THREAD

**Issue by guugg** [roots/bud#813]
### 

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Summary

Hi, how do I use bud in windows

**Comment by QWp6t** [comment]
https://discourse.roots.io/
