### ISSUE TITLE
Building without Babel produces empty builds

### ISSUE THREAD

**Issue by knowler** [roots/bud#82]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Building without Babel produces empty builds.

## Steps to reproduce

https://github.com/knowler/bud-empty-build-repro

**Expected behavior:** [What you expect to happen]

That repo should build the code.

**Actual behavior:** [What actually happens]

It builds an empty file.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time

## Versions

You can get this information from referencing `CHANGELOG.md`. Also, please include the OS and what version of the OS you're running.

- Bud 4.2.0
- Node 16.2.0
- Yarn 1.22.10
- macOS 11.3.1

**Comment by kellymears** [comment]
The issue here has to do with the default js loader used by bud.

Seems like the best course of action is to not give webpack a default loader at all (I'm just passing an empty loader array). I rolled that change into #80.

**Comment by kellymears** [comment]
Also addd the most minimal example possible so we have something to write tests against (https://github.com/roots/bud/pull/80/files#diff-c9b4510ca7b9c8912df3e5119ac0e32c1f9bd73627c57186b50cc28097647f9d)
