### ISSUE TITLE
Sage: Tailwind CSS postcss nesting

### ISSUE THREAD

**Issue by unlocdavid** [roots/bud#823]
### 

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
When using nesting in CSS files in a Sage theme a warning is thrown by Tailwind in the build process when `public` is empty. Tailwind detects the nesting and refers to a doc about configuring nesting. Nesting with just post-css should work wit the Bud sage package.

#### What have you tried?
Use Sass with `bud-sass`. This removes the waring but I'd rather don't use Sass.

#### What insights have you gained?
Although the warning is thrown, the css seems to compile okay.

#### Possible solutions
Implement nesting like described in the [Tailwind docs](https://tailwindcss.com/docs/using-with-preprocessors#nesting)

#### Temporary workarounds
Live with the warning :)

### Steps To Reproduce

1. Add some nested css like:
```
.foo {
  .bar {
    @apply block;
  }
}
```
2. Run `yarn bud clean && yarn build --no-dashboard`

### Expected Behavior

Run the build without warnings.

### Actual Behavior

Warning by Tailwind is thrown.

### Relevant Log Output

```shell
WARNING in ./resources/styles/app.css (./resources/styles/app.css.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[9].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[9].use[2]!./resources/styles/app.css)
  Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
  Warning

  (7:3) Nested CSS was detected, but CSS nesting has not been configured correctly.
  Please enable a CSS nesting plugin *before* Tailwind in your configuration.
  See how here: https://tailwindcss.com/docs/using-with-preprocessors#nesting
   @ ./resources/styles/app.css
```
```


### Versions

5.0.0-next.18

**Comment by kellymears** [comment]
I included a fix for this in https://github.com/roots/bud/pull/824. 

It uses the `tailwindcss/nesting/index.js` postcss plugin exported from `tailwindcss^3.0.0`

**Comment by unlocdavid** [comment]
Bud `5.0.0@next.19` fixes this and some problems I had with live reloading. Thanks!

**Comment by waqas-raza-dh** [comment]
@kellymears 
Sage version 10.0.0-dev
and issue still exists. Build compiles with a warning. 

```
roots/bud/5.0.0 darwin-x64 node-v16.13.0

Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
Warning

(226:7) Nested CSS was detected, but CSS nesting has not been configured correctly.
Please enable a CSS nesting plugin *before* Tailwind in your configuration.
See how here: https://tailwindcss.com/docs/using-with-preprocessors#nesting
```
