### ISSUE TITLE
Bug: `npm install` instead of `yarn` results in errors

### ISSUE THREAD

**Issue by retlehs** [roots/bud#913]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

Bud requires `yarn` instead of `npm install` to properly install dependencies

#### Temporary workarounds

Use `yarn` to install dependencies

### Steps To Reproduce

1. `npm install`
1. `npm run build`

### Expected Behavior

Build should complete without errors

### Actual Behavior

Build errors when dependencies were installed with `npm install` instead of `yarn`

### Relevant Log Output

```shell
[sage] › ℹ  using config from parent compiler
    ValidationError: Invalid configuration object. Webpack has been initialized using a
    configuration object that does not match the API schema.
     - configuration[0].resolve.modules[4] should be a object { alias?, aliasFields?,
    byDependency?, cache?, cachePredicate?, cacheWithContext?, conditionNames?,
    descriptionFiles?, enforceExtension?, exportsFields?, extensions?, fallback?,
    fileSystem?, fullySpecified?, importsFields?, mainFields?, mainFiles?, modules?,
    plugins?, preferAbsolute?, preferRelative?, resolver?, restrictions?, roots?,
    symlinks?, unsafeCache?, useSyncFileSystemCalls? }.
       -> Folder name or directory path where to find modules.
```

### Versions

v5

**Comment by retlehs** [comment]
ℹ️  npm compatibility is being actively investigated but at present we can’t support it. please make sure to use `yarn` for now if you run into this issue

**Comment by kellymears** [comment]
this is related to module resolution with npm. 

it may have been fixed in #922 but we won't know until `5.1.0-next` is released.

## workaround

🚨 this might not be 100% accurate for 5.0.0 but it worked in 5.0.0 pre-release versions (see [original comment](https://github.com/roots/bud/issues/730#issuecomment-981202142)). 

regardless, it also brings to light some valuable information that will help us fix this issue.

from a clean copy of `@roots/sage`:

```
npm install

npm install \
  postcss@8.3.11 \
  @roots/bud-postcss@5.0.0 \
  @roots/bud-eslint@5.0.0 \
  --include dev
  
npx bud build
```

now the build works and we can see expected module resolutions in the log:

```
[sage] [project] › …  analyzing dependencies
[sage] [project] › ✔  resolved @roots/bud-postcss ./node_modules/@roots/bud-postcss
[sage] [project] › ✔  resolved @roots/bud-eslint ./node_modules/@roots/bud-eslint
[sage] [project] › ✔  manifest resolved @roots/bud-postcss
[sage] [project] › ✔  required peer dependency is met postcss@8.3.11
[sage] [project] › ✔  required peer dependency is met postcss-import@14.0.2
[sage] [project] › ✔  required peer dependency is met postcss-nested@5.0.6
[sage] [project] › ✔  required peer dependency is met postcss-preset-env@7.0.1
[sage] [project] › ✔  manifest resolved @roots/bud-eslint
[sage] [project] › ✔  required peer dependency is met eslint@7.32.0
[sage] [project] › ✔  required peer dependency is met prettier@2.4.1
[sage] [project] › …  analyzing devDependencies
[sage] [project] › ✔  resolved @roots/sage ./node_modules/@roots/sage
[sage] [project] › ✔  manifest resolved @roots/sage
[sage] [project] › ✔  resolved @roots/bud-preset-wordpress ./node_modules/@roots/bud-preset-wordpress
[sage] [project] › ✔  resolved @roots/bud-prettier ./node_modules/@roots/bud-prettier
[sage] [project] › ✔  resolved @roots/bud-stylelint ./node_modules/@roots/bud-stylelint
[sage] [project] › ✔  resolved @roots/bud-tailwindcss ./node_modules/@roots/bud-tailwindcss
[sage] [project] › ✔  manifest resolved @roots/bud-preset-wordpress
[sage] [project] › ✔  required peer dependency is met @wordpress/browserslist-config@4.1.0
[sage] [project] › ✔  manifest resolved @roots/bud-prettier
[sage] [project] › ✔  manifest resolved @roots/bud-tailwindcss
[sage] [project] › ✔  required peer dependency is met tailwindcss@2.2.19
[sage] [project] › ✔  manifest resolved @roots/bud-stylelint
[sage] [project] › ✔  resolved @roots/bud-preset-recommend ./node_modules/@roots/bud-preset-recommend
[sage] [project] › ✔  resolved @roots/bud-react ./node_modules/@roots/bud-react
[sage] [project] › ✔  resolved @roots/bud-wordpress-externals ./node_modules/@roots/bud-wordpress-externals
[sage] [project] › ✔  resolved @roots/bud-wordpress-manifests ./node_modules/@roots/bud-wordpress-manifests
[sage] [project] › ✔  resolved @roots/bud-wordpress-dependencies ./node_modules/@roots/bud-wordpress-dependencies
[sage] [project] › ✔  manifest resolved @roots/bud-preset-recommend
[sage] [project] › ✔  manifest resolved @roots/bud-wordpress-externals
[sage] [project] › ✔  manifest resolved @roots/bud-wordpress-manifests
[sage] [project] › ✔  manifest resolved @roots/bud-react
[sage] [project] › ✔  required peer dependency is met react@17.0.2
[sage] [project] › ✔  required peer dependency is met react-dom@17.0.2
[sage] [project] › ✔  manifest resolved @roots/bud-wordpress-dependencies
[sage] [project] › ✔  resolved @roots/bud-babel ./node_modules/@roots/bud-babel
[sage] [project] › ✔  resolved @roots/bud-entrypoints ./node_modules/@roots/bud-entrypoints
[sage] [project] › ✔  manifest resolved @roots/bud-babel
[sage] [project] › ✔  manifest resolved @roots/bud-entrypoints
```

## Problems

- @roots/sage requires a different version of postcss than bud

when there is a mismatch it results in errors that look like this:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: sage@undefined
npm ERR! Found: postcss@8.4.1
npm ERR! node_modules/postcss
npm ERR!   dev postcss@"8.4.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer postcss@"8.3.11" from @roots/bud-postcss@5.0.0-next.16
npm ERR! node_modules/@roots/bud-postcss
npm ERR!   @roots/bud-postcss@"5.0.0-next.16" from the root project
```

i'm not sure what is the best way to keep peer versions in sync between @roots/sage and @roots/bud.

## Refs

- #730
- [npm7 handling of peerDeps](https://github.com/npm/rfcs/blob/main/implemented/0025-install-peer-deps.md#unresolved-questions-and-bikeshedding). 
- relatedly, it would be nice if npm autoinstalled peerDependencies, which [they are considering](https://github.com/npm/rfcs/blob/main/implemented/0025-install-peer-deps.md#f-use-peerdependenciesmeta-to-trigger-auto-install).

**Comment by retlehs** [comment]
if this does not work on the next release, we need to make sure that yarn is added as a requirement to the readme/docs (in sage as well)

**Comment by retlehs** [comment]
fixed as of v5.1.0 🙏

**Comment by rubenmonterogonzalez** [comment]
this is still an issue on ^5.2

**Comment by rubenmonterogonzalez** [comment]
the following failing on both dev / build scripts, on Windows 10, Node v16, yarn & npm

```
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
     - configuration[0].resolve.modules[2] should be a non-empty string.
       -> Folder name or directory path where to find modules.
```

**Comment by retlehs** [comment]
@rubenmonterogonzalez i can't tell if what you're running into is indeed this same issue or not with the context you've provided.

it sounds like you might actually be hitting #914 instead? you said you're on windows, so you should be using WSL.

are you a sage user? if yes, is this from the latest `main` branch code or from a different release? 


1. `git clone git@github.com:roots/sage.git`
2. `npm install`
3. `npm run build`
4. no errors ✅ 

i'm locking this issue since the problem has been resolved, but please submit a bug report or post on roots discourse for support if you're still having trouble
