### ISSUE TITLE
Documentation: Bud requires WSL in order to be ran on Windows

### ISSUE THREAD

**Issue by retlehs** [roots/bud#914]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

Bud isn't correctly working on a Windows environment, unless you're on WSL (**which is highly recommended** 😄 )

### Steps To Reproduce

1. Install Bud on Windows (_without_ WSL)

### Expected Behavior

Bud should run

### Actual Behavior

Bud doesn't run

### Relevant Log Output

```shell
Example #1
----------

(node:15164) [ERR_REQUIRE_ESM] Error Plugin: @roots/bud [ERR_REQUIRE_ESM]: require() of ES Module E:_webDev\bud\node_modules\globby\index.js from E:_webDev\bud\node_modules@oclif\core\lib\config\plugin.js not supported.

Example #2
----------
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration[0].resolve.modules[2] should be a non-empty string.
   -> Folder name or directory path where to find modules.
```

### Versions

v5

**Comment by retlehs** [comment]
my apologies for the sparse report, if any other windows users could report more specifics here it would be helpful

**Comment by AlexMorrisonDev716** [comment]
I just encountered the same error on an M1 Macbook Pro so this certainly isn't isolated to Windows. Have you tried installing globby?

**Comment by retlehs** [comment]
that same error message occurs in multiple bugs, not just this one related to windows. please open a new bug report that is related to whatever it is that you're running into.

**Comment by kellymears** [comment]
@AlexMorrisonDev716 see https://github.com/roots/bud/issues/387#issuecomment-904751331 for a possible fix

**Comment by kellymears** [comment]
I think we start with #941 and then revisit this if it doesn't resolve the issue

**Comment by kellymears** [comment]
WSL is going to be a requirement of bud moving forward. Using this issue to track documentation of that.
