### ISSUE TITLE
Bug: Error when install bud-sass

### ISSUE THREAD

**Issue by Romaixn** [roots/bud#947]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
Error when installing bud-sass

#### What have you tried?
Following the documentation :

`yarn add @roots/bud-sass --dev`
`yarn bud install`

### Steps To Reproduce

1. yarn add @roots/bud-sass sass --dev
2. yarn bud install

### Expected Behavior

`yarn bud install` ensure peer dependencies are met

### Actual Behavior

Error :

`Error: TypeError: app.extensions.get(...).setOption is not a function`

### Versions

bud-sass 5.0.0 and bud 5.0.0-next.16

**Comment by retlehs** [comment]
> Versions
> bud 5.0.0-next.16

please try the latest version (v5) and report back

**Comment by Romaixn** [comment]
Oh yes! The problem is solved, thank you!
