### ISSUE TITLE
Sage Theme: Tailwind CSS Nesting issue

### ISSUE THREAD

**Issue by waqas-raza-dh** [roots/bud#953]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
`yarn dev` and `yarn build` both fail due to nesting in my scss files. 
#### What have you tried?
Tried updating the related packages. 
#### What insights have you gained?
As per the discussion [here](https://github.com/roots/bud/issues/823) the latest bud version solves the issue which is not the case. I am using the latest version of the sage theme v10 and error still exists.
#### Possible solutions
As mentioned on [Tailwind docs](https://tailwindcss.com/docs/using-with-preprocessors#nesting) solution is to add `tailwindcss/nesting` which is a wrapper for `postcss-nested` plugin.  Since, `postcss-nested` is already included in the latest sage theme, build should compile.
#### Temporary workarounds
none

### Steps To Reproduce

1. Import any `scss` file into main `app.css` file.
1. Add the following code to the scss file 
```
p {
  font-size: clamp(.85rem, 3vw, 1rem);
  @apply my-4 leading-normal;

  a {
    @apply underline;
    text-decoration-skip-ink: auto;
    text-underline-offset: 2px;
  }
}
```
3. either run `yarn dev` or `yarn build`

### Expected Behavior

Build should compile without any errors/warnings. 

### Actual Behavior

`yarn dev` and `yarn build` both fail.

### Relevant Log Output

```shell
`yarn dev` fails as following 


Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
Warning

(226:7) Nested CSS was detected, but CSS nesting has not been configured correctly.
Please enable a CSS nesting plugin *before* Tailwind in your configuration.
See how here: https://tailwindcss.com/docs/using-with-preprocessors#nesting

<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/Users/newsage/app/public/wp-content/themes/sage/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[9].use[1]!/Users/newsage/app/public/wp-content/themes/sage/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[9].use[2]!/newsage/app/public/wp-content/themes/sage/resources/styles/app.css': No serializer registered for Warning
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> Array { 1 items } -> webpack/lib/ModuleWarning -> Warning
```
and `yarn build` fails as 
```
/newsage/app/public/wp-content/themes/sage/node_modules/@roots/bud-dashboard/lib/cjs/index.js:76091
throw ex;
^

TypeError: Cannot read properties of undefined (reading 'assets')
at Compilation.createModuleAssets (/newsage/app/public/wp-content/themes/sage/node_modules/webpack/lib/Compilation.js:4413:25)
at /newsage/app/public/wp-content/themes/sage/node_modules/webpack/lib/Compilation.js:3047:13
at /newsage/app/public/wp-content/themes/sage/node_modules/webpack/lib/Compilation.js:3234:5
at /newsage/app/public/wp-content/themes/sage/node_modules/neo-async/async.js:2818:7
at done (/newsage/app/public/wp-content/themes/sage/node_modules/neo-async/async.js:3522:9)
at /newsage/app/public/wp-content/themes/sage/node_modules/webpack/lib/Compilation.js:3214:7
at /newsage/app/public/wp-content/themes/sage/node_modules/webpack/lib/Compilation.js:3302:32
at /newsage/app/public/wp-content/themes/sage/node_modules/webpack/lib/HookWebpackError.js:68:3
at _done (eval at create (/newsage/app/public/wp-content/themes/sage/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
  at Hook.eval [as callAsync] (eval at create (/newsage/app/public/wp-content/themes/sage/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:39:22)
    error Command failed with exit code 7.
```
```


### Versions

10.0.0-beta.2, MacOS

**Comment by JanKruft** [comment]
@waqas-raza-dh did you installed  [postcss-nesting](https://www.npmjs.com/search?q=postcss-nesting) package? For me it is working after installing these package.
