### ISSUE TITLE
Bug: Cannot use yarn dev in internal lan like laravel-mix

### ISSUE THREAD

**Issue by SergiArias** [roots/bud#973]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

In Laravel Mix, using my_internal_ip:3000 from another computer inside the same LAN was able to show the dev page. This is ideal for live feedback. In Bud, it just shows the html but nothing else (no images, no css, nothing).

### Steps To Reproduce

* get you internal IP address using `ifconfig | grep inet`
* run `yarn dev`
* from another computer, load internal_IP:3000

### Expected Behavior

A mirror of what I see on my development computer

### Actual Behavior

The website in the other computer is broken: no images, no css, nothing.

### Versions

10.0.0-beta-2

**Comment by retlehs** [comment]
also reported on roots discourse: https://discourse.roots.io/t/access-site-from-local-network-with-bud/22131/2

**Comment by kellymears** [comment]
This is a feature of browsersync, which mix uses. bud does not use it. Someone could make an extension to support browser-sync but that's not currently on the roadmap for this project.

But! It is pretty easy to set this up on your own with [browser-sync-webpack-plugin](https://github.com/Va1/browser-sync-webpack-plugin):

## Install the plugin and its dependencies

```sh
yarn add browser-sync browser-sync-webpack-plugin --dev
```

## Add the plugin to bud

The [bud.use function](https://budjs.netlify.app/docs/bud.use) allows you to add webpack plugins in your bud config. just require the plugin, add your configuration and pass it as a parameter:

```ts
const bs = require('browser-sync-webpack-plugin')

bud.use(new bs({proxy: 'http://example.com'}))
```

I just tested this and it works well. Browsersync will run on port 3001 because bud's default server is already running on port 3000. Both will run at the same time without issue so you can take advantage of bud's development server while still doing cross-device testing (or whatever your use case is).

Closing this issue now but feel free to ask additional questions if you feel like bud is conflicting with browsersync in some way.

**Comment by areklam** [comment]
I'm trying to get Browsersync working. Does the bud config need to be rewritten from the async syntaxt? No errors in console, but not getting Browsersync running on port 3001.

```
 * @param {bud} app
 */

const bs = require('browser-sync-webpack-plugin')

module.exports = async (app) =>
  app
    /**
     * Application entrypoints
     *
```

```
    /**
     * Target URL to be proxied by the dev server.
     *
     * This is your local dev server.
     */
    .proxy('http://www.tester.test')

    .use(new bs({proxy: 'http://www.tester.test'}));
```

**Comment by transcript-js** [comment]
Works for me @areklam.

My bud.config.js looks like this:

```/**
 * @typedef {import('@roots/bud').Bud} Bud
 *
 * @param {Bud} config
 */

 const bs = require('browser-sync-webpack-plugin')

 module.exports = async (config) =>
   config
     /**
      * Application entrypoints
      *
      * Paths are relative to your resources directory
      */
     .entry({
       app: ['scripts/app.js', 'styles/app.css'],
       editor: ['scripts/editor.js', 'styles/editor.css'],
     })
 
     /**
      * These files should be processed as part of the build 
      * even if they are not explicitly imported in application assets.
      */
     .assets(['resources/images', 'resources/svg'])
 
     /**
      * These files will trigger a full page reload
      * when modified.
      */
     .watch([
       'tailwind.config.js',
       'resources/views/**/*.blade.php',
       'app/View/**/*.php',
     ])
 
     .proxy('http://www.tester.test')
 
     .use(new bs({proxy: 'http://www.tester.test'}));
 ```

**Comment by areklam** [comment]
Still no luck. I've installed BrowserSync and tried both with and without bud async (config) like you @transcript-js have above.

```
✖  TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'instance' -> object with constructor 'BrowserSync'
    --- property 'publicInstance' closes the circle
    at JSON.stringify (<anonymous>)
    at Bud.facade ([secure]/node_modules/@roots/bud-api/lib/cjs/api/facade/facade.factory.js:12:22)
    at module.exports ([secure]/bud.config.js:44:6)
    at Configuration.invoke ([secure]/node_modules/@roots/bud/lib/cjs/cli/Runner/config/dynamic.config.js:93:19)
    at [secure]/node_modules/@roots/bud/lib/cjs/cli/Runner/config/dynamic.config.js:54:24
    at async Promise.all (index 0)
    at async Configuration.run ([secure]/node_modules/@roots/bud/lib/cjs/cli/Runner/config/dynamic.config.js:52:9)
    at async Object.configs ([secure]/node_modules/@roots/bud/lib/cjs/cli/Runner/config/dynamic.config.js:113:9)
    at async Runner.make ([secure]/node_modules/@roots/bud/lib/cjs/cli/Runner/index.js:104:13)
    at async Build.run ([secure]/node_modules/@roots/bud/lib/cjs/cli/commands/build.js:31:9)
[themename] [api] › …  Executing 5 enqueued functions
[themename] [api] › ❯  executing entry [{"app":["scripts/app.js","styles/app.css"],"editor":["scripts/editor.js","styles/editor.css"]}]
[themename] [api] › ❯  executing assets [["images"]]
[themename] [api] › ❯  executing watch [["tailwind.config.js","resources/views/**/*.blade.php","app/View/**/*.php"]]
[themename] [api] › ❯  executing proxy ["http://themename.test"]
[themename] [api] › ❯  enabling proxy
    Error: Error: TypeError: Converting circular structure to JSON
        --> starting at object with constructor 'Object'
        |     property 'instance' -> object with constructor 'BrowserSync'
        --- property 'publicInstance' closes the circle
[themename] [bud] [node] [terminate] › ℹ  exit
```

**Comment by aksld** [comment]
> 

Same error for me ...

**Comment by transcript-js** [comment]
I don't have any idea as I'm not really experienced with Javascript at all. But I noticed just now that there had been updates to Sage and Bud. I'm still on Bud 5.0.0-next.18. Not sure if this matters, though.

--- edit --- 
Just stumbled across #1183 - not totally sure but this looks like it might help.

**Comment by kellymears** [comment]
I want to confirm that #1183 will fix the issues y'all are having.

It should release today but until then setting it up as a proper extension (rather than just a plugin passthrough) will fix the problem:

```ts
bud.use({
    name: 'browser-sync-webpack-plugin',
    make: () => new bs({proxy: 'http://website.test'}),
  })
```

**Comment by SergiArias** [comment]
I can confirm that with version 5.8.7 we don't need browsersync plugin anymore as it works out of the box 😍
